= Eksport til protonregisteret


== Metadata


TemplateId:: export_proton_registry_v30


Archetype:: openEHR-EHR-COMPOSITION.export_secondary_use_dips.v1




:toc:




// Not supported rmType COMPOSITION
== EVENT_CONTEXT
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*EVENT_CONTEXT* + 
EVENT_CONTEXT: __
5+a|*Template versjonsinformasjon* + 
CLUSTER: _openEHR-EHR-CLUSTER.template_semver_dips.v1_
|at0001| 0..1| DV_CODED_TEXT | Navn
a|
* Eksport til protonregisteret (no.onk.export: PROT)
5+a|*Klinisk kontekst* + 
CLUSTER: _openEHR-EHR-CLUSTER.clinical_context_dips.v1_
|at0001| 0..1| DV_CODED_TEXT | Forløpstype
a|
* Sarkom (no.onk.forlopstype: 1)
* Kreft i hode og hals (no.onk.forlopstype: 2)
* Hjernesvulst (no.onk.forlopstype: 3)
* Brystkreft (no.onk.forlopstype: 4)
* Lungekreft (no.onk.forlopstype: 5)
* Kreft i fordøyelsessystemet (no.onk.forlopstype: 6)
* Gynekologisk kreft (no.onk.forlopstype: 7)
* Kreft i nyre og urinveier (no.onk.forlopstype: 8)
* Benmargs- og blodkreft (no.onk.forlopstype: 9)
* Lymfom (no.onk.forlopstype: 10)
* Hudkreft (no.onk.forlopstype: 11)
* Kreft i mannlige kjønnsorganer (no.onk.forlopstype: 12)
* Kreft i endokrine kjertler (no.onk.forlopstype: 13)
* Nevroendokrin kreft (no.onk.forlopstype: 14)
* Barnekreft (no.onk.forlopstype: 15)
* Øyekreft (no.onk.forlopstype: 16)
* Svulst av ukjent opprinnelse / Annet (no.onk.forlopstype: 17)


Feltet vil typisk være skjult for bruker og settes med gjenbruk fra andre felter. 
|====
== Sosialanamnese_generell
== Utdanningssammendrag
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Utdanningssammendrag* + 
EVALUATION: _openEHR-EHR-EVALUATION.education_summary.v1_
|at0002| 0..1| DV_CODED_TEXT | Høyeste fullførte utdanningsnivå
a|
* Ingen utdanning (no.utdanningsnivaa: 0)
* Grunnskole (no.utdanningsnivaa: 1)
* Videregående (no.utdanningsnivaa: 2)
* Universitet/Høyskole <4 år (no.utdanningsnivaa: 3)
* Universitet/Høyskole ≥4 år (no.utdanningsnivaa: 4)
* Ukjent (no.utdanningsnivaa: 9)


Koding av "Høyeste fullførte utdanningsnivå" med en terminologi er anbefalt der det er mulig. For eksempel med NUS 2000 eller Unescos ISCED klassifikasjon. Sistnevnte forefinnes ikke på norsk, men eksempel er "'Upper secondary vocational education"; "Post-secondary non-tertiary vocational education"; "Bachelor’s or equivalent level, professional"; "Doctoral or equivalent level, academic"; "Post-secondary non-tertiary vocational education"; or "Never attended an educational program".
|at0028| 0..1| DV_DATE_TIME | Sist oppdatert
|


Ved implementering av arketypen forutsettes det at dersom en utdanning eller opplæring legges til eller oppdateres i CLUSTER.education_record (Utdanning), vil også denne datoen oppdateres.
|====
== Arbeidssammendrag
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Arbeidssammendrag* + 
EVALUATION: _openEHR-EHR-EVALUATION.occupation_summary.v1_
|at0004| 0..1| DV_CODED_TEXT | Arbeidsstatus
a|
* I arbeid (no.arbeidsstatus: 1)
* Ikke i arbeid (no.arbeidsstatus: 2)
* Alderspensjonist (no.arbeidsstatus: 3)
* Under utdanning/studerer (no.arbeidsstatus: 4)
* Ukjent (no.arbeidsstatus: 9)
5+a|*Arbeidsforhold/rolle* + 
CLUSTER: _openEHR-EHR-CLUSTER.occupation_record.v1_
|at0005| 0..1| DV_TEXT | Tittel/rolle
a|
5+a|*Sykemelding* + 
CLUSTER: _openEHR-EHR-CLUSTER.sick_note_ous.v1_
|at0004| 0..1| DV_DATE_TIME | Sykemelding - fra dato
|


Startdatoen for sykemeldingen.
|at0001| 0..1| DV_DURATION | Varighet
|


Varigheten av sykemeldinsperioden til individet.
|at0009| 0..1| DV_DATE_TIME | Sist oppdatert
|


Ved implementering av arketypen forutsettes det at dersom en arbeidsepisode legges til eller oppdateres, vil også denne datoen oppdateres.
|====
== Sosialt nettverk
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Sosialt nettverk* + 
EVALUATION: _openEHR-EHR-EVALUATION.social_network.v1_
|at0002| 0..1| DV_CODED_TEXT | Samlivsstatus
a|
* Ugift/enslig (no.samlivsstatus: 1)
* Gift/samboer/registrert partner (no.samlivsstatus: 2)
* Enke/enkemann/gjenlevende partner eller samboer (no.samlivsstatus: 3)
* Skilt/separert (no.samlivsstatus: 4)
* Ukjent (no.samlivsstatus: 9)


Verdisettet for dataelementet "Samlivsstatus" er standardisert med bakgrunn i variabler fra SSB (https://www.ssb.no/klass/klassifikasjoner/19).

|at0018| 0..1| DV_TEXT | Kommentar
a|
|at0011| 0..1| DV_DATE_TIME | Sist oppdatert
|


Datoen da samlivsstatus sist ble oppdatert.
|====
== Samlivsform
== Kartleggingspørsmål om sosiale forhold samlivsform
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Kartleggingspørsmål om sosiale forhold samlivsform* + 
OBSERVATION: _openEHR-EHR-OBSERVATION.social_context_screening.v1_
|at0034| 0..1| DV_CODED_TEXT | Kartleggingsformål
a|
* Samlivsform (no.onk.sosiale_forhold: SAM)


Fast verdi som er skjult for bruker. 
5+a|*Spesifikt sosialt forhold* + 
CLUSTER: _at0022_
|at0004| 1..1| DV_CODED_TEXT | Hvilken samlivsform har pasienten?
a|
* Bor alene (Inkl. alene med barn <18) (no.samlivsform: 1)
* Bor med noen (Partner og/eller med barn >18 år, bofelleskap, venner) (no.samlivsform: 2)
* Bor på institusjon/ sykehjem (Fast plass, ikke korttidsopphold. Gjelder også der egen bolig er døgnbemannet) (no.samlivsform: 3)
* Ukjent (no.samlivsform: 9)


Dette elementet tilbyr valg mellom fritekst og kodet tekst. Det er antatt at listen av kodede verdier vil vokse ettersom man identifiserer flere behov. Det er anbefalt å kode "Sosialt forhold" med en terminologi dersom det er mulig - for eksempel relevante termer innen hierarkiet til SNOMED CT's Social context finding hierarchy (SCTID: 108329005). Alternativt som fritekst, for eksempel "Forsørgelsesbyrde", "Sosial isolasjon", "Diskriminering", "Minoritetsstress".
// Not supported rmType ELEMENT
|| 0..1| DV_TEXT | undefined
// text_value -  /content[openEHR-EHR-SECTION.adhoc.v1,'Sosialanamnese_generell']/items[openEHR-EHR-SECTION.adhoc.v1,'Samlivsform']/items[openEHR-EHR-OBSERVATION.social_context_screening.v1,'Kartleggingspørsmål om sosiale forhold samlivsform']/data[at0001]/events[at0002]/data[at0003]/items[at0022]/items[at0051]/value
a|
|| 0..1| DV_DATE_TIME | undefined
// date_time_value -  /content[openEHR-EHR-SECTION.adhoc.v1,'Sosialanamnese_generell']/items[openEHR-EHR-SECTION.adhoc.v1,'Samlivsform']/items[openEHR-EHR-OBSERVATION.social_context_screening.v1,'Kartleggingspørsmål om sosiale forhold samlivsform']/data[at0001]/events[at0002]/data[at0003]/items[at0022]/items[at0051]/value
|
|| 0..1| DV_DURATION | undefined
// duration_value -  /content[openEHR-EHR-SECTION.adhoc.v1,'Sosialanamnese_generell']/items[openEHR-EHR-SECTION.adhoc.v1,'Samlivsform']/items[openEHR-EHR-OBSERVATION.social_context_screening.v1,'Kartleggingspørsmål om sosiale forhold samlivsform']/data[at0001]/events[at0002]/data[at0003]/items[at0022]/items[at0051]/value
|
// Not supported rmType DV_INTERVAL<DV_DATE_TIME>
|| 1..1| DV_DATE_TIME | undefined
// lower -  /content[openEHR-EHR-SECTION.adhoc.v1,'Sosialanamnese_generell']/items[openEHR-EHR-SECTION.adhoc.v1,'Samlivsform']/items[openEHR-EHR-OBSERVATION.social_context_screening.v1,'Kartleggingspørsmål om sosiale forhold samlivsform']/data[at0001]/events[at0002]/data[at0003]/items[at0022]/items[at0051]/value/lower
|
|| 1..1| DV_DATE_TIME | undefined
// upper -  /content[openEHR-EHR-SECTION.adhoc.v1,'Sosialanamnese_generell']/items[openEHR-EHR-SECTION.adhoc.v1,'Samlivsform']/items[openEHR-EHR-OBSERVATION.social_context_screening.v1,'Kartleggingspørsmål om sosiale forhold samlivsform']/data[at0001]/events[at0002]/data[at0003]/items[at0022]/items[at0051]/value/upper
|
// Not supported rmType DV_INTERVAL<DV_DURATION>
|| 1..1| DV_DURATION | undefined
// lower -  /content[openEHR-EHR-SECTION.adhoc.v1,'Sosialanamnese_generell']/items[openEHR-EHR-SECTION.adhoc.v1,'Samlivsform']/items[openEHR-EHR-OBSERVATION.social_context_screening.v1,'Kartleggingspørsmål om sosiale forhold samlivsform']/data[at0001]/events[at0002]/data[at0003]/items[at0022]/items[at0051]/value/lower
|
|| 1..1| DV_DURATION | undefined
// upper -  /content[openEHR-EHR-SECTION.adhoc.v1,'Sosialanamnese_generell']/items[openEHR-EHR-SECTION.adhoc.v1,'Samlivsform']/items[openEHR-EHR-OBSERVATION.social_context_screening.v1,'Kartleggingspørsmål om sosiale forhold samlivsform']/data[at0001]/events[at0002]/data[at0003]/items[at0022]/items[at0051]/value/upper
|
|at0052| 0..1| DV_TEXT | *Overall comment (en)
a|
|====
== Kartlegging omsorgsansvar
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Kartlegging omsorgsansvar* + 
OBSERVATION: _openEHR-EHR-OBSERVATION.social_context_screening.v1_
|at0034| 0..1| DV_CODED_TEXT | Kartleggingsformål
a|
* Kartlegging av om individet har omsorgsansvar (no.onk.sosiale_forhold: OA)


I prosjektet strukturert kreftjournal er det etablert et eget kodeverk for kartleggingsformål. no.onk.sosiale_forhold.
5+a|*Omsorgsperson for barn under 18 år* + 
CLUSTER: _at0022_
|at0004| 1..1| DV_CODED_TEXT | Sosialt forhold
a|
* Ansvarlig for barn under 18 år (no.onk.sosiale_forhold: U18)


Navngiving av et spesifikt sosialt forhold.
|at0005| 0..1| DV_CODED_TEXT | Har pasienten ansvar for barn under 18 år?
a|
* at0023 -> Ja 
* at0024 -> Nei 
* at0027 -> Ukjent 
// Not supported rmType ELEMENT
|| 0..1| DV_TEXT | undefined
// text_value -  /content[openEHR-EHR-SECTION.adhoc.v1,'Sosialanamnese_generell']/items[openEHR-EHR-OBSERVATION.social_context_screening.v1,'Kartlegging omsorgsansvar']/data[at0001]/events[at0002]/data[at0003]/items[at0022,'Omsorgsperson for barn under 18 år']/items[at0051]/value
a|
|| 0..1| DV_DATE_TIME | undefined
// date_time_value -  /content[openEHR-EHR-SECTION.adhoc.v1,'Sosialanamnese_generell']/items[openEHR-EHR-OBSERVATION.social_context_screening.v1,'Kartlegging omsorgsansvar']/data[at0001]/events[at0002]/data[at0003]/items[at0022,'Omsorgsperson for barn under 18 år']/items[at0051]/value
|
|| 0..1| DV_DURATION | undefined
// duration_value -  /content[openEHR-EHR-SECTION.adhoc.v1,'Sosialanamnese_generell']/items[openEHR-EHR-OBSERVATION.social_context_screening.v1,'Kartlegging omsorgsansvar']/data[at0001]/events[at0002]/data[at0003]/items[at0022,'Omsorgsperson for barn under 18 år']/items[at0051]/value
|
// Not supported rmType DV_INTERVAL<DV_DATE_TIME>
|| 1..1| DV_DATE_TIME | undefined
// lower -  /content[openEHR-EHR-SECTION.adhoc.v1,'Sosialanamnese_generell']/items[openEHR-EHR-OBSERVATION.social_context_screening.v1,'Kartlegging omsorgsansvar']/data[at0001]/events[at0002]/data[at0003]/items[at0022,'Omsorgsperson for barn under 18 år']/items[at0051]/value/lower
|
|| 1..1| DV_DATE_TIME | undefined
// upper -  /content[openEHR-EHR-SECTION.adhoc.v1,'Sosialanamnese_generell']/items[openEHR-EHR-OBSERVATION.social_context_screening.v1,'Kartlegging omsorgsansvar']/data[at0001]/events[at0002]/data[at0003]/items[at0022,'Omsorgsperson for barn under 18 år']/items[at0051]/value/upper
|
// Not supported rmType DV_INTERVAL<DV_DURATION>
|| 1..1| DV_DURATION | undefined
// lower -  /content[openEHR-EHR-SECTION.adhoc.v1,'Sosialanamnese_generell']/items[openEHR-EHR-OBSERVATION.social_context_screening.v1,'Kartlegging omsorgsansvar']/data[at0001]/events[at0002]/data[at0003]/items[at0022,'Omsorgsperson for barn under 18 år']/items[at0051]/value/lower
|
|| 1..1| DV_DURATION | undefined
// upper -  /content[openEHR-EHR-SECTION.adhoc.v1,'Sosialanamnese_generell']/items[openEHR-EHR-OBSERVATION.social_context_screening.v1,'Kartlegging omsorgsansvar']/data[at0001]/events[at0002]/data[at0003]/items[at0022,'Omsorgsperson for barn under 18 år']/items[at0051]/value/upper
|
5+a|*Barn som pårørende* + 
CLUSTER: _at0022_
|at0004| 1..1| DV_CODED_TEXT | Sosialt forhold
a|
* Barn som pårørende (no.onk.sosiale_forhold: BPU18)


Navngiving av et spesifikt sosialt forhold.
|at0005| 0..1| DV_CODED_TEXT | Finnes det barn som pårørende?
a|
* at0023 -> Ja 
* at0024 -> Nei 
* at0027 -> Ukjent 
// Not supported rmType ELEMENT
|| 0..1| DV_TEXT | undefined
// text_value -  /content[openEHR-EHR-SECTION.adhoc.v1,'Sosialanamnese_generell']/items[openEHR-EHR-OBSERVATION.social_context_screening.v1,'Kartlegging omsorgsansvar']/data[at0001]/events[at0002]/data[at0003]/items[at0022,'Barn som pårørende']/items[at0051]/value
a|
|| 0..1| DV_DATE_TIME | undefined
// date_time_value -  /content[openEHR-EHR-SECTION.adhoc.v1,'Sosialanamnese_generell']/items[openEHR-EHR-OBSERVATION.social_context_screening.v1,'Kartlegging omsorgsansvar']/data[at0001]/events[at0002]/data[at0003]/items[at0022,'Barn som pårørende']/items[at0051]/value
|
|| 0..1| DV_DURATION | undefined
// duration_value -  /content[openEHR-EHR-SECTION.adhoc.v1,'Sosialanamnese_generell']/items[openEHR-EHR-OBSERVATION.social_context_screening.v1,'Kartlegging omsorgsansvar']/data[at0001]/events[at0002]/data[at0003]/items[at0022,'Barn som pårørende']/items[at0051]/value
|
// Not supported rmType DV_INTERVAL<DV_DATE_TIME>
|| 1..1| DV_DATE_TIME | undefined
// lower -  /content[openEHR-EHR-SECTION.adhoc.v1,'Sosialanamnese_generell']/items[openEHR-EHR-OBSERVATION.social_context_screening.v1,'Kartlegging omsorgsansvar']/data[at0001]/events[at0002]/data[at0003]/items[at0022,'Barn som pårørende']/items[at0051]/value/lower
|
|| 1..1| DV_DATE_TIME | undefined
// upper -  /content[openEHR-EHR-SECTION.adhoc.v1,'Sosialanamnese_generell']/items[openEHR-EHR-OBSERVATION.social_context_screening.v1,'Kartlegging omsorgsansvar']/data[at0001]/events[at0002]/data[at0003]/items[at0022,'Barn som pårørende']/items[at0051]/value/upper
|
// Not supported rmType DV_INTERVAL<DV_DURATION>
|| 1..1| DV_DURATION | undefined
// lower -  /content[openEHR-EHR-SECTION.adhoc.v1,'Sosialanamnese_generell']/items[openEHR-EHR-OBSERVATION.social_context_screening.v1,'Kartlegging omsorgsansvar']/data[at0001]/events[at0002]/data[at0003]/items[at0022,'Barn som pårørende']/items[at0051]/value/lower
|
|| 1..1| DV_DURATION | undefined
// upper -  /content[openEHR-EHR-SECTION.adhoc.v1,'Sosialanamnese_generell']/items[openEHR-EHR-OBSERVATION.social_context_screening.v1,'Kartlegging omsorgsansvar']/data[at0001]/events[at0002]/data[at0003]/items[at0022,'Barn som pårørende']/items[at0051]/value/upper
|
|at0025| 0..1| DV_TEXT | Kommentar
a|
5+a|*Omsorgsperson for personer over 18 år* + 
CLUSTER: _at0022_
|at0004| 1..1| DV_CODED_TEXT | Sosialt forhold
a|
* Ansvarlig for barn/andre over 18 år (no.onk.sosiale_forhold: O18)


Navngiving av et spesifikt sosialt forhold.
|at0005| 0..1| DV_CODED_TEXT | Har pasienten ansvar for egne barn/andre over 18 år?
a|
* at0023 -> Ja 
* at0024 -> Nei 
* at0027 -> Ukjent 
// Not supported rmType ELEMENT
|| 0..1| DV_TEXT | undefined
// text_value -  /content[openEHR-EHR-SECTION.adhoc.v1,'Sosialanamnese_generell']/items[openEHR-EHR-OBSERVATION.social_context_screening.v1,'Kartlegging omsorgsansvar']/data[at0001]/events[at0002]/data[at0003]/items[at0022,'Omsorgsperson for personer over 18 år']/items[at0051]/value
a|
|| 0..1| DV_DATE_TIME | undefined
// date_time_value -  /content[openEHR-EHR-SECTION.adhoc.v1,'Sosialanamnese_generell']/items[openEHR-EHR-OBSERVATION.social_context_screening.v1,'Kartlegging omsorgsansvar']/data[at0001]/events[at0002]/data[at0003]/items[at0022,'Omsorgsperson for personer over 18 år']/items[at0051]/value
|
|| 0..1| DV_DURATION | undefined
// duration_value -  /content[openEHR-EHR-SECTION.adhoc.v1,'Sosialanamnese_generell']/items[openEHR-EHR-OBSERVATION.social_context_screening.v1,'Kartlegging omsorgsansvar']/data[at0001]/events[at0002]/data[at0003]/items[at0022,'Omsorgsperson for personer over 18 år']/items[at0051]/value
|
// Not supported rmType DV_INTERVAL<DV_DATE_TIME>
|| 1..1| DV_DATE_TIME | undefined
// lower -  /content[openEHR-EHR-SECTION.adhoc.v1,'Sosialanamnese_generell']/items[openEHR-EHR-OBSERVATION.social_context_screening.v1,'Kartlegging omsorgsansvar']/data[at0001]/events[at0002]/data[at0003]/items[at0022,'Omsorgsperson for personer over 18 år']/items[at0051]/value/lower
|
|| 1..1| DV_DATE_TIME | undefined
// upper -  /content[openEHR-EHR-SECTION.adhoc.v1,'Sosialanamnese_generell']/items[openEHR-EHR-OBSERVATION.social_context_screening.v1,'Kartlegging omsorgsansvar']/data[at0001]/events[at0002]/data[at0003]/items[at0022,'Omsorgsperson for personer over 18 år']/items[at0051]/value/upper
|
// Not supported rmType DV_INTERVAL<DV_DURATION>
|| 1..1| DV_DURATION | undefined
// lower -  /content[openEHR-EHR-SECTION.adhoc.v1,'Sosialanamnese_generell']/items[openEHR-EHR-OBSERVATION.social_context_screening.v1,'Kartlegging omsorgsansvar']/data[at0001]/events[at0002]/data[at0003]/items[at0022,'Omsorgsperson for personer over 18 år']/items[at0051]/value/lower
|
|| 1..1| DV_DURATION | undefined
// upper -  /content[openEHR-EHR-SECTION.adhoc.v1,'Sosialanamnese_generell']/items[openEHR-EHR-OBSERVATION.social_context_screening.v1,'Kartlegging omsorgsansvar']/data[at0001]/events[at0002]/data[at0003]/items[at0022,'Omsorgsperson for personer over 18 år']/items[at0051]/value/upper
|
|at0052| 0..1| DV_TEXT | *Overall comment (en)
a|
|====
== Fritekst relatert til sosial anamnese
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Fritekst relatert til sosial anamnese* + 
OBSERVATION: _openEHR-EHR-OBSERVATION.progress_note.v1_


Skal ikke være med i eksport til register. 
|at0004| 0..1| DV_TEXT | Fritekst relatert til sosial anamnese
a|
5+a|*Semistrukturert metadata dips* + 
CLUSTER: _openEHR-EHR-CLUSTER.semistrukturert_metadata_dips.v1_
|at0001| 0..1| DV_CODED_TEXT | Klassifisering av informasjon
a|
* Sosial anamnese (no.dips.Freetext.Classification: 01-Oncology-Sosial-anamnese)
|====
== Komorbiditet_utredning
== Kartlegging komorbiditet
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Kartlegging komorbiditet* + 
OBSERVATION: _openEHR-EHR-OBSERVATION.problem_screening.v1_


Svarene kan være selvrapporterte.
|at0034| 0..1| DV_CODED_TEXT | Kartleggingsformål
a|
* Komorbiditet (no.onk.screening.problem: kom)


I prosjektet strukturert kreftjournal er det etablert et eget kodeverk for kartleggingsformål. no.onk.screening.problem.
|at0028| 0..1| DV_CODED_TEXT | Har pasient kjent komorbiditet?
a|
* at0031 -> Ja 
* at0032 -> Nei 
* at0033 -> Ukjent 
|at0043| 0..1| DV_TEXT | Overordnet merknad komorbiditet
a|
|====
== Gruppering ICD10 kapittel
== Forholdsregel
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Forholdsregel* + 
EVALUATION: _openEHR-EHR-EVALUATION.precaution.v1_
|at0002| 1..1| DV_CODED_TEXT | Tilstand: Hovedkapitler ICD-10
a|
* Infeksjonssykdommer og parasittsykdommer, visse sykd. (Kap.I; A00-B99) (no.icd10.kapitler: I)
* Svulster (Kap.II; C00-D48) (no.icd10.kapitler: II)
* Blodsykdommer og sykdom i bloddannende organer og visse tilstander som angår immunsystemet (Kap.III; D50-D89) (no.icd10.kapitler: III)
* Endokrine sykdommer, ernæringssykdommer og metabolske forstyrrelser (Kap.IV; E00-E90) (no.icd10.kapitler: IV)
* Psykiske lidelser og atferdsforstyrrelser (Kap.V; F00-F99) (no.icd10.kapitler: V)
* Nervesystemet, sykdommer (Kap.VI; G00-G99) (no.icd10.kapitler: VI)
* Øyet og øyets omgivelser, sykdommer (Kap.VII; H00-H59) (no.icd10.kapitler: VII)
* Øre og ørebensknute (processus mastoideus), sykdommer (Kap.VIII; H60-H95) (no.icd10.kapitler: VIII)
* Sirkulasjonssystemet, sykdommer (Kap.IX; I00-I99) (no.icd10.kapitler: IX)
* Åndedrettssystemet, sykdommer (Kap.X; J00-J99) (no.icd10.kapitler: X)
* Fordøyelsessystemet, sykdommer (Kap.XI; K00-K93) (no.icd10.kapitler: XI)
* Hud og underhud, sykdommer (Kap.XII; L00-L99) (no.icd10.kapitler: XII)
* Muskel-skjelettsystemet og bindevev, sykdommer (Kap.XIII; M00-M99) (no.icd10.kapitler: XIII)
* Urin- og kjønnsorganer, sykdommer (Kap.XIV; N00-N99) (no.icd10.kapitler: XIV)
* Svangerskap, fødsel og barseltid (Kap.XV; O00-O99) (no.icd10.kapitler: XV)
* Perinatalperioden  - visse tilstander som oppstår (Kap.XVI; P00-P96) (no.icd10.kapitler: XVI)
* Medfødte misdannelser, deformiteter og kromosomavvik (Kap.XVII; Q00-Q99) (no.icd10.kapitler: XVII)
* Symptomer, tegn, unormale kliniske funn og laboratoriefunn, ikke klassifisert annet sted (Kap.XVIII; R00-R99) (no.icd10.kapitler: XVIII)
* Skader, forgiftninger og visse andre konsekvenser av ytre årsaker (Kap.XIX; S00-T98) (no.icd10.kapitler: XIX)


I prosjektet strukturert kreftjournal er det etablert et eget kodeverk for hovedkapitler i ICD-10, no.icd10.kapitler.
|at0003| 0..1| DV_TEXT | Detaljer
a|
|at0004| 0..1| DV_DATE_TIME | Sist oppdatert
|
|====
== ICD10
== Forholdsregel
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Forholdsregel* + 
EVALUATION: _openEHR-EHR-EVALUATION.precaution.v1_
|at0002| 1..1| DV_TEXT | Tilstand: ICD-10
a|


I strukturert kreftjournal er dette elementet koblet til et ICD-10 søk.
|at0003| 0..1| DV_TEXT | Detaljer
a|
|at0004| 0..1| DV_DATE_TIME | Sist oppdatert
|
|====
== Charlson Comorbidity Index (CCI)
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Charlson Comorbidity Index (CCI)* + 
OBSERVATION: _openEHR-EHR-OBSERVATION.charlson_comorbidity_index.v2_
|at0061| 0..1| DV_ORDINAL | Aldersgruppe
a|
* 0 - <50 år 
* 1 - 50-59 år 
* 2 - 60-69 år 
* 3 - 70-79 år 
* 4 - ≥80 år 
|at0012| 0..1| DV_ORDINAL | Myokardinfarkt
a|
* 0 - Nei 
* 1 - Ja Tidligere diagnostisert eller sannsynlig hjerteinfarkt (EKG-forandringer og/eller enzymforandringer).
|at0009| 0..1| DV_ORDINAL | Kronisk hjertesvikt
a|
* 0 - Nei 
* 1 - Ja Anstrengelsesdyspné eller paroksysmal nattlig dyspné og har respondert symptomatisk (eller ved fysisk undersøkelse) på digitalis, diuretika eller midler som reduserer afterload.
|at0006| 0..1| DV_ORDINAL | Perifere vaskulære sykdommer
a|
* 0 - Nei 
* 1 - Ja Claudicatio intermittens, tidligere bypass på grunn av arteriell insuffisiens, tidligere gangren eller akutt arteriell insuffisiens, ubehandlet thorakalt og/eller abdominalt aneurisme (≥6 cm).
|at0015| 0..1| DV_ORDINAL | Cerebrovaskulær hendelse
a|
* 0 - Nei 
* 1 - Ja Cerebrovaskulær hendelse (CVA) eller transitorisk iskemisk anfall (TIA).
|at0018| 0..1| DV_ORDINAL | Demens
a|
* 0 - Nei 
* 1 - Ja Demens eller kronisk kognitiv svikt.
|at0021| 0..1| DV_ORDINAL | Kronisk lungesykdom
a|
* 0 - Nei 
* 1 - Ja Mild, moderat eller alvorlig kronisk lungesykdom.
|at0024| 0..1| DV_ORDINAL | Ulcussykdom
a|
* 0 - Nei 
* 1 - Ja Enhver behandling av magesårsykdom, blødende magesår, eller tidligere transfusjonskrevende behandling av gastrointestinal blødning.
|at0027| 0..1| DV_ORDINAL | Leversykdom
a|
* 0 - Ingen 
* 1 - Mild Cirrhose uten portal hypertensjon eller kronisk hepatitt.
* 3 - Moderat til alvorlig Moderat: Cirrhose med portal hypertensjon, men uten blødning. Alvorlig: Cirrhose med portal hypertensjon og variceblødning.
|at0030| 0..1| DV_ORDINAL | Bindevevssykdom
a|
* 0 - Nei 
* 1 - Ja 
|at0033| 0..1| DV_ORDINAL | Diabetes
a|
* 0 - Ingen eller diettkontrollert 
* 1 - Ukomplisert Diabetes behandlet med insulin eller orale hypoglykemiske midler, men ikke diett alene.
* 2 - Organskade Diabetes med endeorganskade.
|at0036| 0..1| DV_ORDINAL | Hemiplegi
a|
* 0 - Nei 
* 2 - Ja 
|at0039| 0..1| DV_ORDINAL | Moderat til alvorlig nyresykdom
a|
* 0 - Nei 
* 2 - Ja Moderat: kreatinin >3 mg/dL (0,27 mmol/L). Alvorlig: i dialyse, er transplantert, har uremi.
|at0045| 0..1| DV_ORDINAL | Solid svulst
a|
* 0 - Ingen 
* 2 - Lokalisert Solid tumor uten dokumenterte metastaser.
* 6 - Metastatisk Metastatisk solid tumor.
|at0047| 0..1| DV_ORDINAL | Leukemi
a|
* 0 - Nei 
* 2 - Ja 
|at0050| 0..1| DV_ORDINAL | Lymfom
a|
* 0 - Nei 
* 2 - Ja 
|at0060| 0..1| DV_ORDINAL | AIDS
a|
* 0 - Nei 
* 6 - Ja Bekreftet AIDS eller sannsynlig AIDS ved for eksempel påvist AIDS-relatert tilstand.
|at0072| 0..1| DV_COUNT | CCI totalskår
|
|====
== Stimulantia
== Alkohol
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Alkohol* + 
EVALUATION: _openEHR-EHR-EVALUATION.alcohol_consumption_summary.v1_
|at0089| 0..1| DV_CODED_TEXT | Overordnet status
a|
* at0003 -> Nåværende bruker 
* at0005 -> Tidligere bruker 
* at0006 -> Aldri brukt 
|at0043| 0..1| DV_TEXT | Overordnet beskrivelse
a|


Bruk dette elementet for å registrere en beskrivelse i fritekst om drikkevaner for dette individet, eller for å overføre til arketypeformat ustrukturert informasjon om drikkevaner fra et eksisterende eller tidligere brukt klinisk system.
5+a|*Per episode* + 
CLUSTER: _at0064_
|at0023| 0..1| DV_QUANTITY | Typisk bruk (alkoholenheter)
|
|at0022| 0..1| DV_DATE_TIME | Sist oppdatert
|
|====
== Røyk
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Røyk* + 
EVALUATION: _openEHR-EHR-EVALUATION.tobacco_smoking_summary.v1_
|at0089| 0..1| DV_CODED_TEXT | Overordnet status
a|
* at0006 -> Aldri røykt 
* at0003 -> Røyker 
* at0005 -> Tidligere røyker 
|at0043| 0..1| DV_TEXT | Overordnet beskrivelse
a|


Bruk dette datalementet til å registrere en fritekstbeskrivelse av individets tobakksrøykevaner, eller for å overføre ustrukturert informasjon fra eksisterende eller tidligere kliniske systemer til arketypeformat.
|at0074| 0..1| DV_COUNT | Samlet pakkeår
|


Definisjonen på en pakke kan registreres i protokollen av denne arketypen, ved å bruke dataelementet "Pakkedefinisjon".
|at0022| 0..1| DV_DATE_TIME | Sist oppdatert
|
|====
== Røykfri tobakk/snus
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Røykfri tobakk/snus* + 
EVALUATION: _openEHR-EHR-EVALUATION.smokeless_tobacco_summary.v1_
|at0089| 0..1| DV_CODED_TEXT | Overordnet status
a|
* at0006 -> Aldri brukt 
* at0003 -> Nåværende bruker 
* at0005 -> Tidligere bruker 
|at0043| 0..1| DV_TEXT | Overordnet beskrivelse
a|


Bruk dette datalementet til å registrere en fritekstbeskrivelse kun der data som er registrert strukturert ikke reflekterer individets bruk av røykfri tobakk på en tilfredsstillende måte, eller for å overføre ustrukturert informasjon om bruk av røykfri tobakk fra eksisterende eller tidligere kliniske systemer til arketypeformat.
|at0022| 0..1| DV_DATE_TIME | Sist oppdatert
|
|====
== Sammendrag andre substanser
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Sammendrag andre substanser* + 
EVALUATION: _openEHR-EHR-EVALUATION.substance_use_summary.v1_


Tobakksrøyking, bruk av røykfri tobakk, alkoholbruk, damping (vaping) og administrasjon av medikamenter i henhold til etablerte medisinske retningslinjer og standarder er bevisst holdt utenfor konseptet, og skal registreres ved å bruke andre arketyper laget for formålet.
|at0002| 1..1| DV_CODED_TEXT | Substansnavn
a|
* Annen substans (no.onk.substansbruk: osub)


Koding med ekstern terminologi anbefales om det er mulig.
|at0007| 0..1| DV_TEXT | Overordnet beskrivelse
a|


Dette elementet kan også brukes til å ta inn fritekstlige beskrivelser av substansbruk fra eksisterende eller historiske kliniske systemer.
|at0031| 0..1| DV_DATE_TIME | Sist oppdatert
|
|====
== Bivirkningsregistrering
== Bivirkninger av behandling
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Bivirkninger av behandling* + 
OBSERVATION: _openEHR-EHR-OBSERVATION.problem_screening.v1_


Svarene kan være selvrapporterte.
|at0034| 0..1| DV_CODED_TEXT | Kartleggingsformål
a|
* Baseline (no.onk.kart.tidligere_komplikasjoner_kreftbehandling: 1)
* Under behandling (no.onk.kart.tidligere_komplikasjoner_kreftbehandling: 2)


Det er definert et eget kodeverk for å kunne angi enten løpende registreringer under pasientforløpet eller som en baseline registeringer før behandling eller intervensjoner starter. 
5+a|*Komplikasjon/bivirkning* + 
CLUSTER: _at0022_
|at0004| 1..1| DV_CODED_TEXT | Problem/diagnosenavn
a|
* Complication of procedure (SNOMED-CT: 116224001)


Teknisk felt skjult for bruker. 
|at0005| 0..1| DV_CODED_TEXT | Har det oppstått bivirkninger som følge av behandling siden siste kontakt?
a|
* at0023 -> Ja 
* at0024 -> Nei 


Kartleggingsspørsmål som styrer visningen i CTCAE arketypen. Det kan vurderes om dette kan arves teknisk ned til feltet i problem/diagnose arketypen. 
5+a|*Hørsel* + 
CLUSTER: _at0022_
|at0004| 1..1| DV_CODED_TEXT | Subjektiv hørselstap
a|
* hørselstap (SNOMED-CT: 15188001)


Teknisk felt skjult for bruker. 
|at0005| 0..1| DV_CODED_TEXT | Subjektiv svekket hørsel?
a|
* at0023 -> Ja 
* at0024 -> Nei 


Kartleggingsspørsmål som styrer visningen i CTCAE arketypen. Det kan vurderes om dette kan arves teknisk ned til feltet i problem/diagnose arketypen. 
|====
== Problem/diagnose
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Problem/diagnose* + 
EVALUATION: _openEHR-EHR-EVALUATION.problem_diagnosis.v1_


Det er i praksis ikke lett å oppnå et klart skille mellom et problem og en diagnose. I klinisk dokumentasjon med denne arketypen ses problem og diagnose som et kontinuum, med økende krav til detaljer og støttende evidens for å underbygge en diagnose.
|at0002| 1..1| DV_CODED_TEXT | Problem/diagnosenavn
a|
* Complication of procedure (SNOMED-CT: 116224001)


Koding av navnet på problemet eller diagnosen med en terminologi er foretrukket hvis mulig.
|at0079| 0..1| DV_CODED_TEXT | Variant
a|
* Baseline (no.onk.kart.tidligere_komplikasjoner_kreftbehandling: 1)
* Under behandling (no.onk.kart.tidligere_komplikasjoner_kreftbehandling: 2)


For eksempel "akutt motorisk aksonal nevropati" som en variant av Guillain-Barre Syndrom. Koding av navnet på varianten med en terminologi er foretrukket hvis mulig.
|at0009| 0..1| DV_TEXT | Overordnet beskrivelse av bivirkning/komplikasjon
a|


Brukes til å gi bakgrunn og kontekst, inkludert utvikling, episoder eller forverringer, fremgang og alle andre relevante detaljer, om problemet eller diagnosen.
|at0005| 0..1| DV_CODED_TEXT | Alvorlighetsgrad
a|
* at0047 -> Mild 
* at0048 -> Moderat 
* at0049 -> Alvorlig 


Settes automatisk basert på verste CTCAE gradering. Etter reglene: 

0,1 -> Mild 
2 -> Moderat
3,4,5 -> Alvorlig 
5+a|*Common Terminology Criteria for Adverse Events (CTCAE)* + 
CLUSTER: _openEHR-EHR-CLUSTER.ctcae.v1_


Tidligere kjent som Common Toxicity Criteria (CTC).
|at0001| 0..1| DV_CODED_TEXT | Kategori
a|
* Blood and lymphatic system disorders (MEDRA: 1001)


Dette elementet identifiserer et anatomisk eller fysiologisk system, etiologi eller formål.


|at0002| 1..1| DV_CODED_TEXT | Term
a|
* X (MEDRA: X)


Dette elementet kan mappes til den korresponderende MedDRA-koden.
|at0003| 1..1| DV_ORDINAL | Kategori for grad
a|
* 0 - Grad 0 Fravær av en uønsket hendelse eller innenfor normale verdier. Bare for CTC versjon 1 og 2.
* 1 - Grad 1 Mild, ELLER asymptomatisk eller milde symptomer, ELLER kun kliniske eller diagnostiske observasjoner, ELLER ikke grunnlag for intervensjon.
* 2 - Grad 2 Moderat, ELLER minimal, lokal eller indikasjon for ikke-invasiv intervensjon, ELLER begrenser alders-tilpasset ADL.
* 3 - Grad 3 Alvorlig eller medisinsk betydningsfull, men ikke umiddelbart livstruende, ELLER indikasjon for sykehusinnleggelse eller forlengelse av sykehusopphold, ELLER invalidiserende, begrenset evne til egenomsorg og ADL.
* 4 - Grad 4 Livstruende konsekvenser, ELLER indikasjon for øyeblikkelig intervensjon.
* 5 - Grad 5 Død relatert til uønsket medisinsk hendelse.


Den kliniske beskrivelsen for hver "Kategori for grad" er dokumentert i den publiserte spesifikasjonen av CTCAE v5.0. Grad 0 har ikke vært i bruk siden CTCAE v2, men er tatt med for å kunne brukes for alle versjoner av CTCAE.
|at0020| 0..1| DV_CODED_TEXT | Beskrivelse av grad
a|
* A (CTCAETERM: A)


Dette elementet er en plassholder for term eller frase som tilhører en identifisert grad. I de fleste implementasjonene vil det bli utfylt via en eksterne kilde, som en CTCAE kunnskapsbase eller en annen kilde, under kjøring av dataprogrammet (run-time).
|at0009| 0..1| DV_TEXT | CTCAE- versjon
a|
* CTCAE_5.0
5+a|*Subjektiv hørselstap* + 
CLUSTER: _openEHR-EHR-CLUSTER.symptom_sign.v2_
|at0001| 1..1| DV_CODED_TEXT | Navn på symptom/sykdomstegn
a|
* hørselstap (SNOMED-CT: 15188001)


Navnet på symptom/sykdomstegn bør kodes med en terminologi om mulig.
|at0189| 0..1| DV_CODED_TEXT | Karakter
a|
* Subjective observation (qualifier value) (SNOMED-CT: 255362007)


For eksempel: Smerte kan beskrives som "gnagende", "brennende" eller "som et elektrisk støt", mens en hodepine kan være "bankende" eller "konstant". Karakteren bør kodes med en terminologi, der det er mulig.
5+a|*Problem/diagnose-kvalifikator* + 
CLUSTER: _openEHR-EHR-CLUSTER.problem_qualifier.v2_
|at0073| 0..1| DV_CODED_TEXT | Tilstede ved innleggelse?
a|
* at0108 -> Ja 
* at0109 -> Nei 


Benyttes for å angi om komplikasjonen var tilstede ved oppstart behandling. 

Tilsvarer : 
1	Baseline
2	Under behandling

|at0070| 0..1| DV_DATE_TIME | Sist oppdatert
|
|====
== Målinger
== Høyde/Lengde
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Høyde/Lengde* + 
OBSERVATION: _openEHR-EHR-OBSERVATION.height.v2_


Høyde måles stående og lengde liggende.
|at0004| 1..1| DV_QUANTITY | Høyde/lengde
|
|====
== Kroppsvekt
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Kroppsvekt* + 
OBSERVATION: _openEHR-EHR-OBSERVATION.body_weight.v2_
|at0004| 1..1| DV_QUANTITY | Kroppsvekt
|
|====
== Kroppsmasseindeks
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Kroppsmasseindeks* + 
OBSERVATION: _openEHR-EHR-OBSERVATION.body_mass_index.v2_
|at0004| 1..1| DV_QUANTITY | Kroppsmasseindeks
|
|====
== ECOG funksjonsstatus
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*ECOG funksjonsstatus* + 
OBSERVATION: _openEHR-EHR-OBSERVATION.ecog.v1_
|at0004| 1..1| DV_ORDINAL | ECOG funksjonsstatus
a|
* 0 - Asymptomatisk I stand til å utføre enhver normal aktivitet uten begrensning.
* 1 - Symptomatisk, fullt oppegående Ikke i stand til fysisk krevende aktivitet, men oppegående og i stand til å utføre lett arbeid.
* 2 - Symptomatisk, sengeliggende <50 % av våken tid Oppegående og i stand til all egenpleie, men ikke i stand til noe arbeid; oppe og i bevegelse mer enn 50% av våken tid.
* 3 - Symptomatisk, sengeliggende > 50 % av våken tid Bare i stand til begrenset egenpleie, bundet til seng eller stol > 50 % av våken tid.
* 4 - Helt sengeliggende Helt hjelpetrengende; klarer ikke noen egenpleie; helt bundet til seng eller stol.
* 5 - Død Pasienten er død.
|====
== Karnofsky Performance Status (KPS) scale
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Karnofsky Performance Status (KPS) scale* + 
OBSERVATION: _openEHR-EHR-OBSERVATION.karnofsky_performance_status_scale.v1_
|at0004| 1..1| DV_ORDINAL | Karnofsky performance status
a|
* 100 - Normal, ingen plager eller subjektive tegn på sykdom. 
* 90 - Klarer normal aktivitet, sykdommen gir lite symptomer. 
* 80 - Klarer med nød normal aktivitet. Sykdommen gir en del symptomer. 
* 70 - Klarer seg selv, ute av stand til normal aktivitet eller aktivt arbeid. 
* 60 - Trenger noe hjelp, men klarer stort sett å tilfredsstille egne behov. 
* 50 - Trenger betydelig hjelp og stadig medisinsk omsorg. 
* 40 - Ufør, trenger spesiell hjelp og omsorg. 
* 30 - Helt ufør, hospitalisering nødvendig, men fare for død er ikke overhengende. 
* 20 - Svært syk, hospitalisering og understøttende behandling nødvendig. 
* 10 - Moribund, dødsprosessen er i sterk frammarsj. 
* 0 - Død. 
|====
== Tidligere kreftbehandling
== Kartlegging om tidligere kreftbehandling
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Kartlegging om tidligere kreftbehandling* + 
OBSERVATION: _openEHR-EHR-OBSERVATION.procedure_screening.v1_
|at0034| 0..1| DV_CODED_TEXT | Kartleggingsformål
a|
* Tidligere_kreftbehandling (no.onk.kartlegging: 01)


I prosjektet strukturert kreftjournal er det etablert et eget kodeverk for kartleggingsformålet no.onk.kart.tidligere_kreftbehandling.
|at0028| 0..*| DV_CODED_TEXT | Har pasienten hatt tidligere kreftbehandling?
a|
* at0031 -> Ja 
* at0032 -> Nei 
* at0038 -> Ukjent 
|at0041| 0..1| DV_TEXT | Merknad om tidligere kreftbehandling
a|
5+a|*Spesifikk prosedyre* + 
CLUSTER: _at0022_
|at0004| 1..1| DV_CODED_TEXT | Prosedyrenavn
a|
* Kirurgisk fjerning (SNOMED-CT: 128303001)
* Ablation (SNOMED-CT: 64597002)
* Stråleterapi (alle typer) (SNOMED-CT: 1287742003)
* Fotonterapi - Stråle (ekstern) (SNOMED-CT: 1156506007)
* Protonterapi -Stråle (ekstern) (SNOMED-CT: 10611004)
* Elektronterapi - Stråle (ekstern) (SNOMED-CT: 45643008)
* Brakyterapi - Stråle (intern) (SNOMED-CT: 152198000)
* Radioisotope/systemisk radionuklidebehandling - Stråle (intern) (SNOMED-CT: 399315003)
* Medikamentell behandling (alle typer) (SNOMED-CT: 416608005)
* Kjemoterapi - Medikamentell (SNOMED-CT: 367336001)
* Målrettet - Medikamentell (SNOMED-CT: 347531000202105)
* Immunterapi - Medikamentell behandling (SNOMED-CT: 76334006)
* Hormonterapi - Medikamentell (SNOMED-CT: 169413002)
* Annen behandling (SNOMED-CT: 74964007)
* Ingen kreftbehandling, aktiv oppfølging (SNOMED-CT: 373818007)
* Ekseptans (SNOMED-CT: 438758006)
|at0005| 0..1| DV_CODED_TEXT | Utført?
a|
* at0023 -> Ja 
* at0024 -> Nei 
* at0039 -> Ukjent 


Designkommentar:
Denne er som regel skjult og settes som ja hvis man krysser av for prosedyren. 
Hvis man ønsker å få svar ja/nei så må den vises.
|at0037| 0..1| DV_DATE_TIME | Behandlingsstart
|


Designkommentar :
NB! Må ikke endre navn på dette elementet.
Dette pga. uttrekk til sekundærdata
|at0037| 0..1| DV_DATE_TIME | Behandlingsslutt
|


Designkommentar :
NB! Må ikke endre navn på dette elementet.
Dette pga. uttrekk til sekundærdata
|at0025| 0..1| DV_TEXT | Merknad
a|
|====
== problem_oncology_sjk
== Problem/diagnose (inkl TNM)_01
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Problem/diagnose (inkl TNM)_01* + 
EVALUATION: _openEHR-EHR-EVALUATION.problem_diagnosis.v1_


Det er i praksis ikke lett å oppnå et klart skille mellom et problem og en diagnose. I klinisk dokumentasjon med denne arketypen ses problem og diagnose som et kontinuum, med økende krav til detaljer og støttende evidens for å underbygge en diagnose.
|at0002| 1..1| DV_CODED_TEXT | Problem/diagnosenavn
a|
* Neoplastisk sykdom (SNOMED-CT: 55342001)


Klassifiserer primærtumor som en neoplastisk sykdom for gruppering på tvers av kreftformene. 55342001 | neoplastisk sykdom |
|at0009| 0..1| DV_TEXT | Klinisk beskrivelse
a|


Brukes i Sarkom med endret navn til "Merknad" 

Brukes til å gi bakgrunn og kontekst, inkludert utvikling, episoder eller forverringer, fremgang og alle andre relevante detaljer, om problemet eller diagnosen.
|at0012| 0..1| DV_CODED_TEXT | Anatomisk lokalisering
a|
* Erstattes med kode fra script eller gjenbruk (SNOMED-CT: x)


Koding av navnet på den anatomiske lokaliseringen ved hjelp av en terminologi er foretrukket når dette er mulig. 
Bruk dette dataelementet for å registrere prekoordinerte anatomiske lokaliseringer. Dersom behovene for å registrere anatomisk sted bestemmes i applikasjonen eller trenger større grad av kompleksitet som f.eks. relativ lokalisering, er det anbefalt å bruke CLUSTER.anatomical_location eller CLUSTER.relative_location innenfor SLOTet "Strukturert anatomisk lokalisering" i denne arketypen. Dette dataelementet kan ha ubegrenset antall forekomster, for å gjøre det mulig å registrere kliniske scenarier som f.eks. å beskrive et utslett som opptrer flere steder på kroppen, men der alle andre attributter er identiske. Dersom den anatomiske lokaliseringen inkluderes i feltet "Problem/diagnosenavn" via prekoordinerte koder blir dette dataelementet overflødig.
5+a|*Anatomisk lokalisering* + 
CLUSTER: _openEHR-EHR-CLUSTER.anatomical_location.v1_
|at0001| 1..1| DV_CODED_TEXT | Navn på kroppssted
a|
* Erstattes av kreftspesifikk kode (SNOMED-CT: x)
|at0065| 0..*| DV_CODED_TEXT | Spesifikt sted
a|
* Erstattes av kreftspesifikk kode (SNOMED-CT: x)


Brukes tilå øke presisjonen ved spesifisering av kroppsstedet, dersom påkrevd. For eksempel den øvre høyre kvadranten eller McBurneys punkt på bukveggen, eller interfalangealleddet på stortåen. Dersom dataelementet "Navn på kroppssted" er registrert ved hjelp av prekoordinerte termer som omfatter det spesifikke stedet er dette dataelementet overflødig. I de fleste tilfeller vil dette være ett enkelt sted på kroppen. Dataelementet åpner for flere forekomster i de sjeldne tilfellene der man trenger å angi et spesifikt anatomisk sted som omfatter to eller flere sammenhengende spesifikke steder. For eksempel for å beskrive det spesifikke stedet en svulst strekker seg over andre, tredje og fjerde ribben.
|at0002| 0..1| DV_CODED_TEXT | Kroppsside
a|
* at0003 -> Venstre 
* at0004 -> Høyre 


Hvis «Navn på kroppssted» inkluderer et pre-koordinert begrep som allerede angir lateralitet, kan dette dataelementet være overflødig. Hvis funnene krever dokumentasjon av et kroppssted på både venstre og høyre side av kroppen, eller involverer begge sider av en parret struktur eller region, bruk «Venstre og høyre» kun når samme anatomiske sted er involvert på begge sider og side-spesifikke detaljer ikke er nødvendige. Hvis funnene er betydelig forskjellige mellom sidene, bør hver side dokumenteres som en separat instans av denne arketypen med korrekt lateralitet.
|at0023| 0..1| DV_TEXT | Beskrivelse
a|


B
|at0078| 0..1| DV_CODED_TEXT | Årsak
a|
* Stråleindusert (SNOMED-CT: 1340012009)


I Sarkom benyttes feltet kodet med mulig verdi: 

SNOMED-CT::1340012009|Stråleindusert|

Også kjent som 'etiologi'. Det anbefales å kode "Årsak" med en ekstern terminologi dersom det er mulig.
5+a|*Oncology problem details dips* + 
CLUSTER: _openEHR-EHR-CLUSTER.oncology_problem_details_dips.v1_


Benyttes inntil videre da det det kan være at SJK prosjektet har avdekket en mangel av de eksisterende arketypene for kreftområdet. F.eks. kunne det vært aktuelt å benytte TNM arketypen. 
|at0001| 0..1| DV_CODED_TEXT | Multiple primærtumorer
a|
* Multiple primærtumorer (SNOMED-CT: 109359008)


Benyttes for hode/halskreft for å angi forekomst av multiple tumorer med forskjellig morfologi, dvs. at histologien er forskjellig. 
|at0003| 0..1| DV_CODED_TEXT | Multifokal tumor
a|
* Multifokal tumor (SNOMED-CT: 399506006)
|at0002| 0..1| DV_TEXT | Beskrivelse
a|
5+a|*TNM-klassifikasjon klinisk* + 
CLUSTER: _openEHR-EHR-CLUSTER.tnm.v1_


Betegnes som TNM eller cTNM.
|at0003| 0..1| DV_CODED_TEXT | Primærtumor (T)
a|
* cT0 (no.onk.tnm: T0)
* cT1 (no.onk.tnm: T1)
* cT1a (no.onk.tnm: T1a)
* cT1a1 (no.onk.tnm: T1a1)
* cT1a2 (no.onk.tnm: T1a2)
* cT1b (no.onk.tnm: T1b)
* cT1b1 (no.onk.tnm: T1b1)
* cT1b2 (no.onk.tnm: T1b2)
* cT1b3 (no.onk.tnm: T1b3)
* cT1 (no.onk.tnm: T1)
* cT1c1 (no.onk.tnm: T11)
* cT1c2 (no.onk.tnm: T12)
* cT1c3 (no.onk.tnm: T13)
* cT1d (no.onk.tnm: T1d)
* cT1mi (no.onk.tnm: T1mi)
* cT2 (no.onk.tnm: T2)
* cT2a (no.onk.tnm: T2a)
* cT2a1 (no.onk.tnm: T2a1)
* cT2a2 (no.onk.tnm: T2a2)
* cT2b (no.onk.tnm: T2b)
* cT2 (no.onk.tnm: T2)
* cT2d (no.onk.tnm: T2d)
* cT3 (no.onk.tnm: T3)
* cT3a (no.onk.tnm: T3a)
* cT3b (no.onk.tnm: T3b)
* cT3 (no.onk.tnm: T3)
* cT3d (no.onk.tnm: T3d)
* cT3e (no.onk.tnm: T3e)
* cT4 (no.onk.tnm: T4)
* cT4a (no.onk.tnm: T4a)
* cT4b (no.onk.tnm: T4b)
* cT4 (no.onk.tnm: T4)
* cT4d (no.onk.tnm: T4d)
* cT4e (no.onk.tnm: T4e)
* cTX (no.onk.tnm: TX)
* cTa (no.onk.tnm: Ta)
* cTis (no.onk.tnm: Tis)
* cTis(DCIS) (no.onk.tnm: Tis(DIS))
* cTis(LAMN) (no.onk.tnm: Tis(LAMN))
* cTis(Paget) (no.onk.tnm: Tis(Paget))


Kodes med en T-kode som passer for tumortypen og den anatomiske lokaliseringen, for eksempel "T1" eller "T3". Fremkommer i "TNM-vurdering" som "T" eller "cT".
|at0004| 0..1| DV_CODED_TEXT | Regionale lymfeknuter (N)
a|
* cN0 (no.onk.tnm: N0)
* cN0(i+) (no.onk.tnm: N0(i+))
* cN0a (no.onk.tnm: N0a)
* cN0b (no.onk.tnm: N0b)
* cN1 (no.onk.tnm: N1)
* cN1a (no.onk.tnm: N1a)
* cN1b (no.onk.tnm: N1b)
* cN1 (no.onk.tnm: N1)
* cN1mi (no.onk.tnm: N1mi)
* cN2 (no.onk.tnm: N2)
* cN2a (no.onk.tnm: N2a)
* cN2b (no.onk.tnm: N2b)
* cN2 (no.onk.tnm: N2)
* cN2mi (no.onk.tnm: N2mi)
* cN3 (no.onk.tnm: N3)
* cN3a (no.onk.tnm: N3a)
* cN3b (no.onk.tnm: N3b)
* cN3 (no.onk.tnm: N3)
* cNX (no.onk.tnm: NX)


Kodes med en N-kode som passer for tumortypen og den anatomiske lokaliseringen, for eksempel "NX" eller "cN2". Fremkommer i "TNM-vurdering" som "N" eller "cN".
|at0005| 0..1| DV_CODED_TEXT | Fjernmetastase (M)
a|
* cM0 (no.onk.tnm: M0)
* cM0(i+) (no.onk.tnm: M0(i+))
* cM1 (no.onk.tnm: M1)
* cM1a (no.onk.tnm: M1a)
* cM1a(0) (no.onk.tnm: M1a(0))
* cM1a(1) (no.onk.tnm: M1a(1))
* cM1b (no.onk.tnm: M1b)
* cM1b(0) (no.onk.tnm: M1b(0))
* cM1b(1) (no.onk.tnm: M1b(1))
* cM1 (no.onk.tnm: M1)
* cM1c(0) (no.onk.tnm: M1(0))
* cM1c(1) (no.onk.tnm: M1(1))
* cM1c1 (no.onk.tnm: M11)
* cM1c2 (no.onk.tnm: M12)
* cM1d (no.onk.tnm: M1d)
* cM1d(0) (no.onk.tnm: M1d(0))
* cM1d(1) (no.onk.tnm: M1d(1))


Kodes med en M-kode som passer for tumortypen og den anatomiske lokaliseringen, for eksempel "M1", "cM1a", "M1 PUL" eller or "cM0". Fremkommer i "TNM-vurdering" som "M" eller "cM".
|at0027| 0..1| DV_BOOLEAN | Residiv (r)
|


Angis ved å legge til prefikset "r" i "TNM-vurdering".
|at0030| 0..1| DV_TEXT | TNM-vurdering
a|
|at0031| 0..1| DV_CODED_TEXT | Stadium
a|
* Stadium 0 (no.onk.tnm.stadium: 0)
* Stadium l (no.onk.tnm.stadium: l)
* Stadium ll (no.onk.tnm.stadium: ll)
* Stadium lll (no.onk.tnm.stadium: lll)
* Stadium lV (no.onk.tnm.stadium: lV)
* Stadium V (no.onk.tnm.stadium: V)


For eksempel: Karsinom in situ er kategorisert som stadium 0, tumorer med fjernmetastaser er kategorisert som stadium IV.
|at0032| 0..1| DV_CODED_TEXT | TNM-utgave
a|
* UICC TNM Versjon 8 (UICC-TNM-VERSION: Edition8)
* UICC TNM Versjon 9 (UICC-TNM-VERSION: Edition9)
5+a|*TNM-klassifikasjon patologi* + 
CLUSTER: _openEHR-EHR-CLUSTER.tnm-pathological.v1_


Betegnes som pTNM.
|at0003.1| 0..1| DV_CODED_TEXT | Primærtumor (pT)
a|
* pT0 (no.onk.tnm: pT0)
* pT1 (no.onk.tnm: pT1)
* pT1a (no.onk.tnm: pT1a)
* pT1a1 (no.onk.tnm: pT1a1)
* pT1a2 (no.onk.tnm: pT1a2)
* pT1b (no.onk.tnm: pT1b)
* pT1b1 (no.onk.tnm: pT1b1)
* pT1b2 (no.onk.tnm: pT1b2)
* pT1b3 (no.onk.tnm: pT1b3)
* pT1c (no.onk.tnm: pT1c)
* pT1c1 (no.onk.tnm: pT1c1)
* pT1c2 (no.onk.tnm: pT1c2)
* pT1c3 (no.onk.tnm: pT1c3)
* pT1d (no.onk.tnm: pT1d)
* pT1mi (no.onk.tnm: pT1mi)
* pT2 (no.onk.tnm: pT2)
* pT2a (no.onk.tnm: pT2a)
* pT2a1 (no.onk.tnm: pT2a1)
* pT2a2 (no.onk.tnm: pT2a2)
* pT2b (no.onk.tnm: pT2b)
* pT2c (no.onk.tnm: pT2c)
* pT2d (no.onk.tnm: pT2d)
* pT3 (no.onk.tnm: pT3)
* pT3a (no.onk.tnm: pT3a)
* pT3b (no.onk.tnm: pT3b)
* pT3c (no.onk.tnm: pT3c)
* pT3d (no.onk.tnm: pT3d)
* pT4 (no.onk.tnm: pT4)
* pT4a (no.onk.tnm: pT4a)
* pT4b (no.onk.tnm: pT4b)
* pT4c (no.onk.tnm: pT4c)
* pT4d (no.onk.tnm: pT4d)
* pT4e (no.onk.tnm: pT4e)
* pTX (no.onk.tnm: pTX)
* pTa (no.onk.tnm: pTa)
* pTis (no.onk.tnm: pTis)
* pTis(DCIS) (no.onk.tnm: pTis(DCIS))
* pTis(LAMN) (no.onk.tnm: pTis(LAMN))
* pTis(Paget) (no.onk.tnm: pTis(Paget))


Kodes med en T-kode som passer for tumortypen og den anatomiske lokaliseringen, for eksempel "pT1" eller "pT3". Fremkommer i "TNM-vurdering" som "pT".
|at0004.1| 0..1| DV_CODED_TEXT | Regionale lymfeknuter (pN)
a|
* pN0 (no.onk.tnm: pN0)
* pN0(i+) (no.onk.tnm: pN0(i+))
* pN0(mol+) (no.onk.tnm: pN0(mol+))
* pN0a (no.onk.tnm: pN0a)
* pN1 (no.onk.tnm: pN1)
* pN1a (no.onk.tnm: pN1a)
* pN1a(sn) (no.onk.tnm: pN1a(sn))
* pN1b (no.onk.tnm: pN1b)
* pN1c (no.onk.tnm: pN1c)
* pN1mi (no.onk.tnm: pN1mi)
* pN2 (no.onk.tnm: pN2)
* pN2a (no.onk.tnm: pN2a)
* pN2b (no.onk.tnm: pN2b)
* pN2c (no.onk.tnm: pN2c)
* pN2mi (no.onk.tnm: pN2mi)
* pN3 (no.onk.tnm: pN3)
* pN3a (no.onk.tnm: pN3a)
* pN3b (no.onk.tnm: pN3b)
* pN3c (no.onk.tnm: pN3c)
* pNX (no.onk.tnm: pNX)


Kodes med en N-kode som passer for tumortypen og den anatomiske lokaliseringen, for eksempel "pNX" eller "pN2". Fremkommer i "TNM-vurdering" som "pN".
|at0005.1| 0..1| DV_CODED_TEXT | Fjernmetastase (pM)
a|
* pM1 (no.onk.tnm: pM1)
* pM1a (no.onk.tnm: pM1a)
* pM1a(0) (no.onk.tnm: pM1a(0))
* pM1a(1) (no.onk.tnm: pM1a(1))
* pM1b (no.onk.tnm: pM1b)
* pM1b(0) (no.onk.tnm: pM1b(0))
* pM1b(1) (no.onk.tnm: pM1b(1))
* pM1c (no.onk.tnm: pM1c)
* pM1c(0) (no.onk.tnm: pM1c(0))
* pM1c(1) (no.onk.tnm: pM1c(1))
* pM1d (no.onk.tnm: pM1d)
* pM1d(0) (no.onk.tnm: pM1d(0))
* pM1d(1) (no.onk.tnm: pM1d(1))


Kodes med en M-kode som passer for tumortypen og den anatomiske lokaliseringen, for eksempel "pM1. Fremkommer i "TNM-vurdering" som "pM".
|at0027| 0..1| DV_BOOLEAN | Residiv (r)
|


Angis ved å legge til prefikset "r" i "TNM-vurdering".
|at0030.1| 0..1| DV_TEXT | pTNM-vurdering
a|
|at0032| 0..1| DV_CODED_TEXT | TNM-utgave
a|
* UICC TNM Versjon 8 (UICC-TNM-VERSION: Edition8)
* UICC TNM Versjon 9 (UICC-TNM-VERSION: Edition9)
5+a|*Problem/diagnose detaljer* + 
CLUSTER: _openEHR-EHR-CLUSTER.problem_diagnosis_dips.v1_


Benyttes for å sette ICD10 koder for problemer hvor det er mer aktuelt å bruke overordnet kode på problem/diagnosenavn. 
|at0001| 0..1| DV_CODED_TEXT | Diagnosenavn
a|


Benyttes for ICD-10 koding av primærtumor. 
|at0003| 0..1| DV_TEXT | Beskrivelse
a|
5+a|*Problem/diagnose-kvalifikator* + 
CLUSTER: _openEHR-EHR-CLUSTER.problem_qualifier.v2_


2.mai 2025 
Utkast til struktur for å angi progresjon og residiv knyttet til hhv. lokalt, regionalt og metastase. 
Vi bruker feltene i arketypen for progresjon og bedringsfase for å uttrykke hhv. progresjon og residiv. 
I tillegg legges manifisteringen (lokalt, metastase, etc.) inn i feltet forekomst. 

Det ser ut til å være en struktur som følger arketypen godt. 
|at0102| 0..1| DV_CODED_TEXT | Progresjon
a|
* at0105 -> I forverring 


For eksempel status for kreft eller en hematologisk diagnose.
|at0083| 0..1| DV_CODED_TEXT | Residiv
a|
* at0097 -> Residivert 


For eksempel for å spore tilhelingen av en mellomørebetennelse.
|at0071| 0..1| DV_CODED_TEXT | Forekomst
a|
* Lokalt (no.onc.tumorevent.hendelse: 01)
* Regionalt (no.onc.tumorevent.hendelse: 02)
* Metastasert (no.onc.tumorevent.hendelse: 03)
* Biokjemisk (no.onc.tumorevent.hendelse: 04)


Dette dataelementet kan brukes som en ytterligere kvalifikator i tillegg til verdien "Ny" i elementet "Episodisitet". For eksempel kan en sykdom som astma ha gjentakende episoder med bedre perioder mellom, men det kan likevel være viktig å kunne identifisere den første astmaepisoden fra de påfølgende.
5+a|*Utredningsmetode* + 
CLUSTER: _openEHR-EHR-CLUSTER.clinical_evidence.v1_
|at0003| 0..1| DV_CODED_TEXT | Grunnlag
a|
* Neoplastisk sykdom (SNOMED-CT: 55342001)
* Metastatic malignant neoplasm (disorder) (SNOMED-CT: 128462008)
* Regional lymph node metastasis present (finding) (SNOMED-CT: 399374009)


Settes fast til neplastisk sykdom for primærtumor, men det er jo et spørsmål om denne er relevant å  ha med 
|at0006| 0..1| DV_DATE_TIME | Dato
|


For eksempel når en klinisk undersøkelse ble gjort. For laboratorieanalyser eller bildediagnostikk er dette dato/tid for når prøven eller bildet ble tatt.
|at0022| 0..*| DV_CODED_TEXT | Metode
a|
* Klinisk vurdering (SNOMED-CT: 58147004)
* Palpasjon (SNOMED-CT: 113011001)
* Bildediagnostikk (SNOMED-CT: 363679005)
* Cytologi (SNOMED-CT: 116147009)
* Biopsi (SNOMED-CT: 86273004)
* Reseksjon (SNOMED-CT: 65801008)
* Annet (SNOMED-CT: 74964007)
* Ukjent (SNOMED-CT: 69466000)


Metoden bør vurderes kodet med en terminologi der dette er mulig. For eksempel fysisk undersøkelse, røntgen thorax, patologisvar, koloskopi.
|at0001| 0..1| DV_TEXT | Spesifiser annen metode
a|
|at0073| 0..1| DV_CODED_TEXT | Diagnostisk sikkerhet
a|
* at0074 -> Mistenkt 
* at0076 -> Bekreftet 


Hvis et alternativt verdisett er nødvendig, kan disse verdiene legges til DV_TEXT-datatypen i et templat.
|at0069| 0..1| DV_TEXT | Kommentar diagnose/TNM
a|
|at0070| 0..1| DV_DATE_TIME | Sist oppdatert
|
|====
== problem_oncology_lymph_node_sjk
== Regional lymfeknutemetastase_10
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Regional lymfeknutemetastase_10* + 
EVALUATION: _openEHR-EHR-EVALUATION.problem_diagnosis.v1_


Det er i praksis ikke lett å oppnå et klart skille mellom et problem og en diagnose. I klinisk dokumentasjon med denne arketypen ses problem og diagnose som et kontinuum, med økende krav til detaljer og støttende evidens for å underbygge en diagnose.
|at0002| 1..1| DV_CODED_TEXT | Regional lymfeknutemetastase
a|
* Regional lymph node metastasis present (finding) (SNOMED-CT: 399374009)


Bruker SNOMED-CT koden 399374009 - Regional lymph node metastasis present (finding), for å klassifisisere problemet. 
|at0079| 0..1| DV_TEXT | Variant
a|


Designkommentar:
Denne blir i Brystkreft brukt til ICD10 koder for regional lymfeknutemetastase. 
Ved andre kreftformer kan det være at denne er overflødig.
5+a|*Utredningsmetode regionale lymfeknutemetastaser* + 
CLUSTER: _openEHR-EHR-CLUSTER.clinical_evidence.v1_
|at0003| 0..1| DV_CODED_TEXT | Grunnlag
a|
* Regional lymph node metastasis present (finding) (SNOMED-CT: 399374009)
|at0006| 0..1| DV_DATE_TIME | Dato
|


Benyttes i Sarkom for dato den regionale lymfeknutemetastasen ble påvist. 

For eksempel når en klinisk undersøkelse ble gjort. For laboratorieanalyser eller bildediagnostikk er dette dato/tid for når prøven eller bildet ble tatt.
|at0022| 0..*| DV_CODED_TEXT | Metode
a|
* Bildediagnostikk (SNOMED-CT: 363679005)
* Cytologi (SNOMED-CT: 116147009)
* Biopsi (SNOMED-CT: 86273004)
* Fjerning av SN (SNOMED-CT: 443497002)
* Reseksjon (SNOMED-CT: 65801008)
* Annet (SNOMED-CT: 74964007)
* Ukjent (SNOMED-CT: 69466000)


Metoden bør vurderes kodet med en terminologi der dette er mulig. For eksempel fysisk undersøkelse, røntgen thorax, patologisvar, koloskopi.
|at0001| 0..1| DV_TEXT | Spesifiser annen metode
a|
5+a|*Anatomisk lokalisering* + 
CLUSTER: _openEHR-EHR-CLUSTER.anatomical_location.v1_


Bryst benytter ikke anatomi på denne registreringen. Sarkom har anatomisk lokalisering. Da er det en anatomi per regionale lymfeknutemetastaser. 

Dersom f.eks. bryst skal registrere anatomi vil det være aktuelt å repetere anatomisk 
|at0001| 1..1| DV_CODED_TEXT | Navn på kroppssted
a|
* Lymfeknute (SNOMED-CT: 59441001)


Angir hvor den regionale lymfeknutemetastasen ble funnet. 
Brystkreft bruker p.t ingen anatomisk lokalisering. Den er da implisitt til aksille. 

Koden for annet kroppsted er 
74964007 - annen (qualifier value) 
|at0002| 0..1| DV_CODED_TEXT | Kroppsside
a|
* at0003 -> Venstre 
* at0004 -> Høyre 
|at0023| 0..1| DV_TEXT | Beskrivelse
a|


For eksempel: Tilgrensende til leppens overgang fra slimhinne til hud; en tatovering dekker nedre halvdel av dette området.
|at0070| 0..1| DV_DATE_TIME | Sist oppdatert
|
|====
== problem_oncology_metastasis_sjk
== Metastase
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Metastase* + 
EVALUATION: _openEHR-EHR-EVALUATION.problem_diagnosis.v1_


Detaljer om funnet av regional lymfeknutemetastase (cN). 
Designkommentar:
Dukker opp om M er annet enn 0 eller X
|at0002| 1..1| DV_CODED_TEXT | Metastase
a|
* Metastatic malignant neoplasm (disorder) (SNOMED-CT: 128462008)


Designkommentar:
Denne vises ikke i skjermbildet. 
Bruker disorder kode for metastase. 
Setter i variant om det er regional eller fjernmetastase.
|at0079| 0..1| DV_CODED_TEXT | Variant
a|
* Regional (SNOMED-CT: 410674003)
* Fjern (SNOMED-CT: 261007001)


Designkommentar:
Anatomisk lokalisering av fjernmetastasen. Lagrer direktelokalisasjon av fjernmetastasen. Hvis ikke koden ligger her må man skrive det inn i fritekst.
Koden for disse er:
410674003	Regional (qualifier value)
261007001	Distant (qualifier value)

5+a|*Utredning metastase* + 
CLUSTER: _openEHR-EHR-CLUSTER.clinical_evidence.v1_


Designkommentar:
Hvis det skal beskrives metode og dato per kroppsdel metastasen befinner seg må denne gjentas.
|at0003| 0..1| DV_CODED_TEXT | Grunnlag
a|
* Metastatic malignant neoplasm (disorder) (SNOMED-CT: 128462008)


Designkommentar:
Denne visis ikke i skjermbildet. 
|at0006| 0..1| DV_DATE_TIME | Dato
|


Designkommentar:
Dato for funn av metastase
|at0022| 0..*| DV_CODED_TEXT | Metode
a|
* Klinisk vurdering (SNOMED-CT: 58147004)
* Palpasjon (SNOMED-CT: 113011001)
* Bildediagnostikk (SNOMED-CT: 363679005)
* Cytologi (SNOMED-CT: 116147009)
* Biopsi (SNOMED-CT: 86273004)
* Reseksjon (SNOMED-CT: 65801008)
* Annet (SNOMED-CT: 74964007)
* Ukjent (SNOMED-CT: 69466000)


Designkommentar:
Typen undersøkelse eller utredning som er utført for å komme fram til funn av fjernmetastasen.
Her er det tenkt at man kan ha flere utredningsmetoder. 
|at0001| 0..1| DV_TEXT | Spesifiser annen metode
a|
5+a|*Anatomisk lokalisering* + 
CLUSTER: _openEHR-EHR-CLUSTER.anatomical_location.v1_


Designkommentar:
Dette clusteret må gjentas for hver kroppssted metastasen befinner seg.
|at0001| 1..1| DV_CODED_TEXT | Navn på kroppssted
a|
* Lunge (SNOMED-CT: 39607008)
* Skjelett (SNOMED-CT: 113192009)
* CNS (sentralnervesystemet) (SNOMED-CT: 21483005)
* Lymfeknuter (SNOMED-CT: 59441001)
* Aksillær lymfeknute (SNOMED-CT: 68171009)
* Lever (SNOMED-CT: 10200004)
* Bløtvev (SNOMED-CT: 87784001)
* Retroperitoneum (SNOMED-CT: 82849001)
* Peritoneum (SNOMED-CT: 15425007)
* Periosteum (SNOMED-CT: 33840008)
* Abdominale organer annet enn lever (SNOMED-CT: 699602007)
* Hjerne (SNOMED-CT: 12738006)
* Benmarg (SNOMED-CT: 14016003)
* Hjerne (SNOMED-CT: 12738006)
* Hud (SNOMED-CT: 39937001)
* Muskulatur (SNOMED-CT: 71616004)
* Pleura (SNOMED-CT: 3120008)
* Tarm (SNOMED-CT: 113276009)
* Magesekk (SNOMED-CT: 69695003)
* Urinveier (SNOMED-CT: 431938005)
* Annet (SNOMED-CT: 74964007)
|at0002| 0..1| DV_CODED_TEXT | Kroppsside
a|
* at0003 -> Venstre 
* at0004 -> Høyre 
|at0023| 0..1| DV_TEXT | Beskrivelse
a|
|at0070| 0..1| DV_DATE_TIME | Sist oppdatert
|
|====
== Bildediagnostikk
== Kartlegging bildediagnostikk
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Kartlegging bildediagnostikk* + 
OBSERVATION: _openEHR-EHR-OBSERVATION.investigation_screening.v1_


Svarene kan være selvrapporterte.
|at0040| 0..1| DV_CODED_TEXT | Kartleggingsformål
a|
* Bildediagnostikk (no.onk.kartlegging: 02)


Design kommentar: Benytter den spesifikk kodeliste for kartlegging innenfor SJK 
|at0027| 0..1| DV_CODED_TEXT | Er bildediagnostiske undersøkelser gjennomført?
a|
* at0028 -> Ja 
* at0029 -> Nei 
* at0030 -> Ukjent 


Designkommentar:
Dette er inngangsspørsmålet om det i det hele tatt er gjort noe bildediagnostikk. 
Dette har man med for å få en avkreftelse om det faktisk er tatt stilling til spm. mao. egentlig for å få med alternativet nei. 
|at0043| 0..1| DV_TEXT | Overordnet beskrivelse bildediagnostiske undersøkelse
a|


Designkommentar:
Her kan man skrive et resyme for alle bildediagnostiske undersøkelser uten å spesifisere nærmere hvilken modalitet man faktisk har utført. 
5+a|*Spesifikk undersøkelse* + 
CLUSTER: _at0026_


Bruk separate instanser av dette CLUSTER'et for å skille mellom spesifikke undersøkelser eller gruppering av undersøkelser.
|at0021| 1..1| DV_CODED_TEXT | Undersøkelsesnavn
a|
* Røntgen (DICOM_modality: RG)
* Mammografi (DICOM_modality: MG)
* Ultralyd (DICOM_modality: US)
* CT (DICOM_modality: CT)
* MR (DICOM_modality: MR)
* Nukleærmedisin (DICOM_modality: NM)
* PET (DICOM_modality: PT)
* PET-CT (DICOM_modality: PTCT)
* PET-MR (DICOM_modality: PTMR)
* Annen modalitet (DICOM_modality: OT)


For eksempel: "Blodgass"," Røntgen thorax", "EKG" eller "Hørseltest". Koding av "Undersøkelsesnavn" med en terminologi foretrekkes der det er mulig.
|at0024| 0..1| DV_CODED_TEXT | Utført?
a|
* at0036 -> Ja 
* at0037 -> Nei 
* at0039 -> Ukjent 


Navnet på dataelementet kan omformuleres til det spesifikke spørsmålet i et templat eller brukergrensesnitt. Det foreslåtte verdisettet kan tilpasses/endres i det enkelte bruksområde ved å benytte de alternative datatypene DV_TEXT eller DV_BOOLEAN.
|at0047| 0..*| DV_TEXT | Type
a|


For eksempel: kontrastforsterket mammografi, forstørrelsesmammografi, digital tomosyntese av bryst, kontrastbildeteknikk, fluorescens in situ hybridisering (FISH), immunoassay-metode.
|at0003| 0..*| DV_DATE_TIME | Tidsangivelse
|


Elementet "Tidsangivelse" er med hensikt løst modellert for å legge til rette for myriadene av mulighetene det kan brukes i spørreskjemaer for å fange når en undersøkelse ble utført. Den spesifikke og tiltenkte semantikken kan bli ytterligere klargjort i et templat. For eksempel: Undersøkelsens faktiske dato og/eller klokkeslett, start- og slutttid for undersøkelsen, et tidsintervall for når undersøkelsen ble gjort, varigheten av en undersøkelse, individets alder på tidspunktet for undersøkelsen, eller hvor lenge det siden den ble gjort. Kan være en delvis dato, for eksempel bare år, ved å bruke datatypen DV_DATE_TIME.
|at0002| 0..1| DV_TEXT | Konklusjon
a|


For eksempel "Alle resultater innenfor normalverdier", "Normal", "Ytterligere undersøkelser nødvendig". Dette dataelementet er ikke tenkt å representere det faktiske resultatet eller funnet til et laboratorieresultat. Er det nødvendig kan en passende CLUSTER-arketype benyttes i  SLOT'et "Ytterligere detaljer", for eksempel CLUSTER.laboratory_test_analyte arketypen (Analyseresultat).
5+a|*Bildediagnostisk undersøkelse - kroppsstruktur* + 
CLUSTER: _openEHR-EHR-CLUSTER.imaging_exam.v1_
|at0001| 1..1| DV_CODED_TEXT | Kroppsstruktur
a|
* Caput (hode) (SNOMED-CT: 69536005)
* Columna vertebralis (ryggrad) (SNOMED-CT: 421060004)
* Thorax (brystkasse) (SNOMED-CT: 51185008)
* Mamma (bryst) (SNOMED-CT: 76752008)
* Aksille (SNOMED-CT: 91470000)
* Lunge (SNOMED-CT: 39607008)
* Abdomen (SNOMED-CT: 818983003)
* Lever (SNOMED-CT: 10200004)
* Pleura (SNOMED-CT: 3120008)
* Pelvis (bekken) (SNOMED-CT: 12921003)
* Skjelett (SNOMED-CT: 113192009)


Bruker et utvalg av kroppsdeler basert på SNOMED-CT koder. 
|====
== Sykdomsutvikling (tumor event)
== Kartlegging av Sykdomsutvikling (tumor event)
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Kartlegging av Sykdomsutvikling (tumor event)* + 
OBSERVATION: _openEHR-EHR-OBSERVATION.problem_screening.v1_


Svarene kan være selvrapporterte.
|at0034| 0..1| DV_CODED_TEXT | Kartleggingsformål
a|
* Tumorhendelse (no.onk.kartlegging: 03)


Dette dataelementet er ment for å sette en kontekst for spørsmålene, dersom man senere ønsker å gjøre spørringer på dataene. Det er ikke forventet at dette dataelementet skal være synlig for en bruker av skjemaet, men kun tilgjengelig i de lagrede dataene. For eksempel: "Preoperativ screening" eller navnet på det faktiske spørreskjemaet.
5+a|*Spesifikt problem eller diagnose* + 
CLUSTER: _at0022_
|at0004| 1..1| DV_CODED_TEXT | Problem/diagnosenavn
a|
* Tumorhendelse (patologisk prosess) (SNOMED-CT: 308489006)


Koding av problem/diagnosenavnet med en terminologi foretrekkes, der det er mulig.
|at0005| 0..1| DV_BOOLEAN | Har det skjedd sykdomsutvikling (tumor event) siden sist kontakt?
|


Navnet på dataelementet kan omformuleres til det spesifikke spørsmålet i et templat eller brukergrensesnitt. Det foreslåtte verdisettet kan tilpasses/endres i det enkelte bruksområde ved å benytte de alternative datatypene DV_TEXT eller DV_BOOLEAN.
|at0040| 0..1| DV_DATE_TIME | Hendelsestidspunkt
|


Dataelementet "Tidsangivelse" er med hensikt løst modellert for å støtte ulike måter å angi tidsangivelser for bekymringen, plagen, problemet eller diagnosen i et spørreskjema. Den konkrete semantikken defineres i templatet. For eksempel: Bekymringen, plagen, problemet eller diagnosen faktiske dato og/eller klokkeslett, start- og slutttid for bekymringen, plagen, problemet eller diagnosen, et tidsintervall for når bekymringen, plagen, problemet eller diagnosen oppstod, varigheten av bekymringen, plagen, problemet eller diagnosen, individets alder på tidspunktet for bekymringen, plagen, problemet eller diagnosen, eller hvor lenge det siden det oppstod. Kan være en deldato, for eksempel bare år, ved å bruke datatypen DV_DATE_TIME.
5+a|*Tumor hendelse dips* + 
CLUSTER: _openEHR-EHR-CLUSTER.tumor_hendelse_dips.v1_
|at0008| 0..1| DV_DATE_TIME | Dato for forrige sykdomsutvikling (tumor event)
|
|====
== Problem/diagnose
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Problem/diagnose* + 
EVALUATION: _openEHR-EHR-EVALUATION.problem_diagnosis.v1_


Det er i praksis ikke lett å oppnå et klart skille mellom et problem og en diagnose. I klinisk dokumentasjon med denne arketypen ses problem og diagnose som et kontinuum, med økende krav til detaljer og støttende evidens for å underbygge en diagnose.
|at0002| 1..1| DV_TEXT | Problem/diagnosenavn (hentet fra ander dokumenter hvis de finnes)
a|


Koding av navnet på problemet eller diagnosen med en terminologi er foretrukket, der det er mulig.
|at0079| 0..*| DV_TEXT | Variant
a|


For eksempel "akutt motorisk aksonal nevropati" som en variant av Guillain-Barre Syndrom. Koding av navnet på varianten med en terminologi er foretrukket hvis mulig.
5+a|*Problem/diagnose-kvalifikator* + 
CLUSTER: _openEHR-EHR-CLUSTER.problem_qualifier.v2_
|at0089| 0..1| DV_CODED_TEXT | Residiv eller progresjon
a|
* Residiv (av tumor) (SNOMED-CT: 25173007)
* Progresjon (SNOMED-CT: 419835002)


For eksempel status for kreft eller en hematologisk diagnose.
|at0071| 0..1| DV_CODED_TEXT | Forekomst
a|
* Lokalt (no.onc.tumorevent.hendelse: 01)
* Regionalt (no.onc.tumorevent.hendelse: 02)
* Metastasert (no.onc.tumorevent.hendelse: 03)
* Biokjemisk (no.onc.tumorevent.hendelse: 04)


Dette dataelementet kan brukes som en ytterligere kvalifikator i tillegg til verdien "Ny" i elementet "Episodisitet". For eksempel kan en sykdom som astma ha gjentakende episoder med bedre perioder mellom, men det kan likevel være viktig å kunne identifisere den første astmaepisoden fra de påfølgende.
5+a|*Klinisk grunnlag* + 
CLUSTER: _openEHR-EHR-CLUSTER.clinical_evidence.v1_
|at0003| 0..1| DV_CODED_TEXT | Funn
a|
* Tumorhendelse (patologisk prosess) (SNOMED-CT: 308489006)


Det anbefales å kode "Funn" med en terminologi, der det er mulig.
|at0005| 0..*| DV_CODED_TEXT | Resultat
a|
* Lokalt (no.onc.tumorevent.hendelse: 01)
* Regionalt (no.onc.tumorevent.hendelse: 02)
* Metastasert (no.onc.tumorevent.hendelse: 03)
* Biokjemisk (no.onc.tumorevent.hendelse: 04)


For eksempel "11 mm", "13 µg/L", "2.5 ml" or "BRCA1 positiv". "Resultat" kan bli kodet med en terminologi der det er passende.
|at0006| 0..1| DV_DATE_TIME | Dato
|


For eksempel når en klinisk undersøkelse ble gjort. For laboratorieanalyser eller bildediagnostikk er dette dato/tid for når prøven eller bildet ble tatt.
|at0022| 0..*| DV_CODED_TEXT | Metode
a|
* Biokjemisk test (SNOMED-CT: 41289000)
* Klinisk (fysisk) undersøkelse (SNOMED-CT: 5880005)
* Bildediagnostikk (SNOMED-CT: 363679005)
* Histologisk test (SNOMED-CT: 714797009)


Metoden bør vurderes kodet med en terminologi der dette er mulig. For eksempel fysisk undersøkelse, røntgen thorax, patologisvar, koloskopi.
|at0001| 0..1| DV_TEXT | Beskrivelse av påvisningsmetode
a|
|at0023| 0..1| DV_TEXT | Kommentar
a|
|at0073| 0..1| DV_CODED_TEXT | Diagnostisk sikkerhet
a|
* at0074 -> Mistenkt 
* at0075 -> Sannsynlig 
* at0076 -> Bekreftet 


Hvis et alternativt verdisett er nødvendig, kan disse verdiene legges til DV_TEXT-datatypen i et templat.
|at0070| 0..1| DV_DATE_TIME | Sist oppdatert
|
|====
== Samtykke informasjon gitt og studier
== Reservasjon til Norsk proton og stråleterapiregister
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Reservasjon til Norsk proton og stråleterapiregister* + 
ACTION: _openEHR-EHR-ACTION.informed_consent_dips.v1_
|at0002| 1..1| DV_CODED_TEXT | Prosedyre/utprøving/aktivitet
a|
* Informert pasienten om reservasjonsrett til Norsk proton- og stråleterapiregister (medisinsk kvalitetsregister) (OncologyConsents: 01)
|====
== Forholdsregel
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Forholdsregel* + 
EVALUATION: _openEHR-EHR-EVALUATION.precaution.v1_
|at0002| 1..1| DV_CODED_TEXT | Navn på studie
a|


Koding av tilstanden med en terminologi er ønskelig, dersom mulig.
|at0014| 0..1| DV_CODED_TEXT | Status
a|
* at0015 -> Aktiv 


Beslutningsstøtte vil typisk utløse advarsler for "Aktiv", og ignorere "Opphørt" eller "Avkreftet". Kliniske systemer kan velge å ikke vise registreringer med status "Avkreftet" i en liste. Likevel kan "Avkreftet" være nyttig for sammenstilling av ulike lister eller ved kommunikasjon mellom systemer. Noen systemer kan velge å gjøre dette elementet obligatorisk. "Opphørt" kan brukes ulikt i ulike systemer avhengig av klinisk bruk og kontekst. Fritekst-datatypen tillater lokal variasjon ved å gjøre det mulig å bruke andre verdisett for dette dataelementet i en templat. Det er i denne situasjonen anbefalt å kode verdiene med en terminologi.
|at0008| 0..1| DV_TEXT | Kommentar
a|
5+a|*Person* + 
CLUSTER: _openEHR-EHR-CLUSTER.person.v1_
|at0001| 0..1| DV_TEXT | Navn
a|


Innholdet i dette elementet kan være en sammenstilling av en eller flere komponenter fra arketypen CLUSTER.structured_name. For eksempel: "John Markham", "Professor Sir John Markham", "John Markham Jnr MP".
|at0004| 0..1| DV_DATE_TIME | Sist oppdatert
|
|====
== biomarkorer
== Kartlegging genetisk biomarkør
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Kartlegging genetisk biomarkør* + 
OBSERVATION: _openEHR-EHR-OBSERVATION.investigation_screening.v1_


Svarene kan være selvrapporterte.
|at0040| 0..1| DV_CODED_TEXT | Kartleggingsformål
a|
* Biomarkor (no.onk.kartlegging: 04)


I prosjektet strukturert kreftjournal er det etablert et eget kodeverk for kartleggingsformål av biomarkører: no.onk.kart.biomarkor
|at0027| 0..1| DV_CODED_TEXT | Er det utført analyser av biomarkører?
a|
* at0028 -> Ja 
* at0029 -> Nei 
* at0030 -> Ukjent 
|at0043| 0..1| DV_TEXT | Overordnet merknad biomarkører
a|
5+a|*Spesifikk undersøkelse* + 
CLUSTER: _at0026_


Dette clusteret kan repeteres for å tilrettelegge for ytterligere spørsmål. F.eks: Er det gjort analyse for gentetiske biomarkører?
|at0021| 1..1| DV_CODED_TEXT | Undersøkelsesnavn
a|
* Genetiske biomarkører (no.onk.type_biomarkorer: B1)
* Biokjemiske biomarkører (no.onk.type_biomarkorer: B2)
|at0024| 0..1| DV_CODED_TEXT | Utført?
a|
* at0036 -> Ja 
* at0037 -> Nei 
* at0039 -> Ukjent 


For eksempel "Er det utført analyser av genetiske biomarkører?"
|at0047| 0..*| DV_TEXT | Type
a|


For eksempel: kontrastforsterket mammografi, forstørrelsesmammografi, digital tomosyntese av bryst, kontrastbildeteknikk, fluorescens in situ hybridisering (FISH), immunoassay-metode.
|====
== Biomarkør Genetikk
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Biomarkør Genetikk* + 
OBSERVATION: _openEHR-EHR-OBSERVATION.laboratory_test_result.v1_
// Not supported rmType POINT_EVENT
|at0005| 1..1| DV_CODED_TEXT | Undersøkelsesnavn
a|
* Genetic test (procedure) (SNOMED-CT: 405824009)


Designkommentar:
Her er det satt genetisk testing som undersøkelsesnavn. 
405824009 - Genetic test (procedure)

5+a|*Prøvemateriale* + 
CLUSTER: _openEHR-EHR-CLUSTER.specimen.v1_


For eksempel kroppsvev eller kroppsvæske.
|at0029| 0..1| DV_CODED_TEXT | Type prøvemateriale
a|
* Blodprøve (SNOMED-CT: 119297000)
* Spinalvæskeprøve (SNOMED-CT: 258450006)
* Vevsprøve (SNOMED-CT: 119376003)
* Benmargsprøve (SNOMED-CT: 119359002)


Designkommentar:
Her er det brukt Specimen koden i SNOMED-CT 
*119297000	Blodprøve
*258450006	Spinalvæskeprøve
*119376003	Vevsprøve
*119359002	Benmargsprøve



|at0007| 0..1| DV_CODED_TEXT | Prøvetakingsmetode
a|
* Sylinder-, grovnål-, pistol-, tru-cut-, eller stansebiopsi av mamma (SNOMED-CT: 122548005)
* Vakuumbiopsi av lesjon i mamma (SNOMED-CT: 771625002)
* Kirurgisk biopsi av mamma (SNOMED-CT: 274331003)
* Eksisjonsbiopsi av mamma med preoperativ lokalisering (Diagnostisk kirurgisk merkebiopsi) (SNOMED-CT: 10940003)
* Biopsi av aksillær lymfeknute (grovnål) (SNOMED-CT: 234271004)
* Kirurgisk eksisjon av lymfeknute (tilfeldig funn av lymfeknute) (lymfadenektomi) (SNOMED-CT: 58347006)
* FNAC (finnålsaspirasjon) av mamma (SNOMED-CT: 387736007)
* FNAC (finnålsaspirasjon) av lymfeknute i aksille (SNOMED-CT: 234282007)


Her må man legge inn type biopsier. 
kan ha biopsi på overordnet nivå. Finne kode for dette. 

Legge inn type prøvetakning: blodprøve
5+a|*Anatomisk lokalisering* + 
CLUSTER: _openEHR-EHR-CLUSTER.anatomical_location.v1_


Designkommentar:
Hvis man ønsker å legge inn hvor prøvematerialet ble tatt fra. Dette gjelder spesielt hvis man ønsker å angi hvilken/hvor en lesjon er anatomisk lokalisert hvis man skal undersøke denne for biokjemiske markører.
|at0001| 1..1| DV_CODED_TEXT | Navn på kroppssted
a|
* x (SNOMED-CT: x)


Designkommentar:
Hvis man ønsker å legge inn hvor prøvematerialet ble tatt fra. Dette gjelder spesielt hvis man ønsker å angi hvilken/hvor en lesjon er anatomisk lokalisert hvis man skal undersøke denne for biokjemiske markører. Relevante SNOMED-CT koder legges til i templatet.
|at0002| 0..1| DV_CODED_TEXT | Kroppsside
a|
* at0003 -> Venstre 
* at0004 -> Høyre 
|at0015| 0..1| DV_DATE_TIME | Dato/tid for prøvetaking
|


N/A

5+a|*Analyseresultat* + 
CLUSTER: _openEHR-EHR-CLUSTER.laboratory_test_analyte.v1_
|at0024| 0..1| DV_CODED_TEXT | Analysenavn
a|
* 13q14.2 (ARL11) (HGNC: HGNC:24046)
* APC (HGNC: HGNC:583)
* ATM (HGNC: HGNC:795)
* BAP1 (HGNC: HGNC:950)
* BARD1 (HGNC: HGNC:952)
* BMPR1A (HGNC: HGNC:1076)
* BRAF (HGNC: HGNC:1097)
* BRCA1 (HGNC: HGNC:1100)
* BRCA2 (HGNC: HGNC:1101)
* BRIP1 (HGNC: HGNC:20473)
* CDC73 (HGNC: HGNC:16783)
* CDH1 (HGNC: HGNC:1748)
* CDK4 (HGNC: HGNC:1773)
* CDKN1B (HGNC: HGNC:1785)
* CDKN2A (HGNC: HGNC:1787")
* CHEK2 (HGNC: HGNC:16627)
* CTNNA1 (HGNC: HGNC:2509)
* CTNNB1 (HGNC: HGNC:2514)
* DICER1 (HGNC: HGNC:17098)
* EGFR (HGNC: HGNC:3236)
* EPCAM (HGNC: HGNC:11529)
* FH (HGNC: HGNC:3700)
* FLCN(Birt-Hogg-Dubé syndrom) (HGNC: HGNC:27310)
* FOXL2 (HGNC: HGNC:1092)
* GREM1 (HGNC: HGNC:2001)
* H3-3A (HGNC: HGNC:4764)
* H3C14 (HGNC: HGNC:20503)
* H3C2 (HGNC: HGNC:4776)
* H3C3 (HGNC: HGNC:4768)
* HOXB13 (HGNC: HGNC:5112)
* HRD status (HGNC: HGNC:11582)
* IDH1 (HGNC: HGNC:5382)
* IDH2 (HGNC: HGNC:5383)
* KIT (HGNC: HGNC:6342)
* KRAS (HGNC: HGNC:6407)
* MAX (HGNC: HGNC:6913)
* MEN1 (HGNC: HGNC:7010)
* MET (HGNC: HGNC:7029)
* MGMT-metylering (HGNC: HGNC:7059)
* MITF (HGNC: HGNC:7105)
* MLH1 (HGNC: HGNC:7127)
* MSH2 (HGNC: HGNC:7325)
* MSH3 (HGNC: HGNC:7326)
* MSH6 (HGNC: HGNC:7329)
* MUTYH (HGNC: HGNC:7527)
* NBN (HGNC: HGNC:7652)
* NF1 (HGNC: HGNC:7765)
* NRAS (HGNC: HGNC:7989)
* NTHL1 (HGNC: HGNC:8028)
* NTRK1 (HGNC: HGNC:8031)
* NTRK2 (HGNC: HGNC:8032)
* NTRK3 (HGNC: HGNC:8033)
* PALB2 (HGNC: HGNC:26144)
* PDGFRA (HGNC: HGNC:8803)
* PMS2 (HGNC: HGNC:9122)
* POLD1 (HGNC: HGNC:9175)
* POLE (HGNC: HGNC:9177)
* POT1 (HGNC: HGNC:17284)
* PRKAR1A (HGNC: HGNC:9388)
* PRSS1 (HGNC: HGNC:9475)
* PTEN (HGNC: HGNC:9588)
* RAD51C (HGNC: HGNC:9820)
* RAD51D (HGNC: HGNC:9823)
* RB1 (HGNC: HGNC:9884)
* RET (HGNC: HGNC:9967)
* RNF43 (HGNC: HGNC:18505)
* SDHA (HGNC: HGNC:10680)
* SDHAF2 (HGNC: HGNC:26034)
* SDHB (HGNC: HGNC:10681)
* SDHC (HGNC: HGNC:10682)
* SDHD (HGNC: HGNC:10683)
* SMAD3 (HGNC: HGNC:6769)
* SMAD4 (HGNC: HGNC:6770)
* SMARCA4 (HGNC: HGNC:11100)
* SMARCB1 (HGNC: HGNC:11103)
* SPINK1 (HGNC: HGNC:11244)
* STK11 (HGNC: HGNC:11389)
* TERT (HGNC: HGNC:11730)
* TMEM127 (HGNC: HGNC:26038)
* TP53 (HGNC: HGNC:11998)
* TSC1 (HGNC: HGNC:12362)
* TSC2 (HGNC: HGNC:12363)
* VHL (HGNC: HGNC:12687)
* WT1 (HGNC: HGNC:12796)


Kodes med HUGO Gene Nomenclature Committee Gene Names (HGNC)
https://www.genenames.org/
Koden skal være med HGNC:nummer, eks: HGNC:1100 (=BRCA1)

|at0001| 0..*| DV_CODED_TEXT | Analyseresultat
a|
* Påvist (tilstede) (SNOMED-CT: 52101004)
* Ikke påvist (ikke tilstede) (SNOMED-CT: 2667000)
* Ikke utført (SNOMED-CT: 385660001)


Vanlig svar fra LOINC
*Present [The target variant is present.]
[LOINC(2.65)::LA9633-4]
*Absent [The target variant is absent.]
[LOINC(2.65)::LA9634-2]
*No call [No data are available to confirm the presence/absence of the variant.]
[LOINC(2.65)::LA18198-4]
*Indeterminate [The result is indeterminate.]
[LOINC(2.65)::LA11884-6]

Svar/verdier på norsk (brukt i lab sammenheng)
*52101004 Påvist (tilstede)
*2667000 Ikke påvist (ikke tilstede) 
*82334004 Ubestemt (indeterminate) = Variant av usikker begydning 
*?? No call (ingen avlesning) (finnes ingen SNOMED-CT kode)

 




|undefined| 1..1| DV_DATE_TIME | Time
|
5+a|*Rekvisisjonsdetaljer* + 
CLUSTER: _at0094_


I de fleste situasjoner finnes det én rekvisisjon og ett korresponderende svar, men under noen omstendigheter kan flere rekvisisjoner representeres ved hjelp av en enkelt laboratorieresultat-arketype.

For eksempel kan en kliniker bestille "glukose" i en rekvisisjon og "urea og elektrolytter" i en ytterligere rekvisisjon, mens laboratoriet utfører begge analysene og sender en samlet rapport.
|at0063| 0..1| DV_TEXT | Rekvisisjonsnummer
a|
|====
== Biomarkør biokjemisk markør
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Biomarkør biokjemisk markør* + 
OBSERVATION: _openEHR-EHR-OBSERVATION.laboratory_test_result.v1_
|at0005| 1..1| DV_CODED_TEXT | Undersøkelsesnavn
a|
* Kjemisk analyse (kvalitativ og kvantativ) (SNOMED-CT: 9336009)


15220000	15220000 | Laboratory test |
116147009	116147009 | cytologisk test |
405824009	405824009 | Genetic test |
714797009	714797009 | Histologic test |
9336009	9336009 | Chemical test, qualitative and quantitative |

5+a|*Prøvemateriale* + 
CLUSTER: _openEHR-EHR-CLUSTER.specimen.v1_


For eksempel kroppsvev eller kroppsvæske.
|at0029| 0..1| DV_CODED_TEXT | Type prøvemateriale
a|
* Blodprøve (SNOMED-CT: 119297000)
* Spinalvæskeprøve (SNOMED-CT: 258450006)
* Vevsprøve (SNOMED-CT: 119376003)
* Benmargsprøve (SNOMED-CT: 119359002)


Designkommentar:
Her er det brukt Specimen koden i SNOMED-CT 
*119297000	Blodprøve
*258450006	Spinalvæskeprøve
*119376003	Vevsprøve
*119359002	Benmargsprøve

|at0007| 0..1| DV_CODED_TEXT | Prøvetakingsmetode
a|
* Blodprøvetaking (SNOMED-CT: 82078001)
* Spinalpunksjon (SNOMED-CT: 277762005)
* Biopsi (SNOMED-CT: 86273004)
* Aspirasjon (SNOMED-CT: 14766002)


Designkommentar:
Prosedyrekoder for prøvetakningsmetode:
*82078001	Blodprøvetaking
*277762005	Spinalpunksjon
*86273004	Biopsi
*14766002	Aspirasjon

|at0015| 0..1| DV_DATE_TIME | Dato/tid for prøvetaking
|


N/A

5+a|*Analyseresultat* + 
CLUSTER: _openEHR-EHR-CLUSTER.laboratory_test_analyte.v1_
|at0024| 0..1| DV_CODED_TEXT | Analysenavn
a|
* x (NLK: x)


Her brukes NLK - norsk laboratoriekodeverk

Må utarbeides mappingtabell som inneholder navn, enhet, metode etc.
Alternativt fritekst?
// Not supported rmType ELEMENT
|| 0..1| DV_QUANTITY | undefined
// quantity_value -  /content[openEHR-EHR-SECTION.adhoc.v1,'biomarkorer']/items[openEHR-EHR-OBSERVATION.laboratory_test_result.v1,'Biomarkør biokjemisk markør']/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.laboratory_test_analyte.v1]/items[at0001]/value
|
|| 0..1| DV_CODED_TEXT | undefined
// coded_text_value -  /content[openEHR-EHR-SECTION.adhoc.v1,'biomarkorer']/items[openEHR-EHR-OBSERVATION.laboratory_test_result.v1,'Biomarkør biokjemisk markør']/data[at0001]/events[at0002]/data[at0003]/items[openEHR-EHR-CLUSTER.laboratory_test_analyte.v1]/items[at0001]/value
a|
* Negativt (SNOMED-CT: 260385009)
* Positivt (SNOMED-CT: 10828004)
* Inkonklusiv (SNOMED-CT: 419984006)
* Ikke utført (SNOMED-CT: 385660001)
|at0004| 0..1| DV_TEXT | Veileder for referanseområde
a|


Designkommentar:
Hvis det finnes to resultater og man har en verdi som er positive/negativ ut i fra kvantitative mål, kan man bruke dette elementet. 

*For eksempel Rubella IgG: 20 IU/mL   Positiv.
Første resultat vil vanligvis være numerisk. Andre resultat en tekststreng. Annet resultat skal kunne utledes av det første ved hjelp av algoritme.



5+a|*Rekvisisjonsdetaljer* + 
CLUSTER: _at0094_
|at0063| 0..1| DV_TEXT | Rekvisisjonsnummer
a|
|====
== Behandlingsoppsummering
== Overordnet behandlingdetaljer
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Overordnet behandlingdetaljer* + 
EVALUATION: _openEHR-EHR-EVALUATION.intervention_summary.v0_
|at0003| 1..1| DV_CODED_TEXT | Behandling for krefttype
a|
* Sarkom (no.onk.kreftgruppering: 01)
* Kreft i hode og hals (no.onk.kreftgruppering: 02)
* Hjernesvulst (no.onk.kreftgruppering: 03)
* Brystkreft (no.onk.kreftgruppering: 04)
* Lungekreft (no.onk.kreftgruppering: 05)
* Kreft i fordøyelsessystemet (no.onk.kreftgruppering: 06)
* Gynekologisk kreft (no.onk.kreftgruppering: 07)
* Kreft i nyre og urinveier (no.onk.kreftgruppering: 08)
* Benmargs- og blodkreft (no.onk.kreftgruppering: 09)
* Lymfom (no.onk.kreftgruppering: 10)
* Hudkreft (no.onk.kreftgruppering: 11)
* Kreft i mannlige kjønnsorganer (no.onk.kreftgruppering: 12)
* Kreft i endokrine kjertler (no.onk.kreftgruppering: 13)
* Nevroendokrin kreft (no.onk.kreftgruppering: 14)
* Barnekreft (no.onk.kreftgruppering: 15)
* Øyekreft (no.onk.kreftgruppering: 16)
* Svulst av ukjent opprinnelse / Annet (no.onk.kreftgruppering: 17)


For eksempel: antibiotika, stråleterapi.
Koding med en terminologi er foretrukket, dersom det er mulig.
|at0058| 0..1| DV_CODED_TEXT | Intervensjonstype
a|
* Kreftbehandling (no.onk.behandlingstype: 1)


18.mars 2025: Valg av kode er under arbeid. Planlagt møte med HDIR

1	Kreftbehandling
225334002	| Intervention regime (regime/therapy) |
413737006	413737006 | Cancer hospital treatment completed (situation) |



*The type of intervention.

grouping of the interventions.
supertype, her kan man ha f.eks. den overordnede grupperingen. .  (en)
|at0028| 0..1| DV_TEXT | Beskrivelse
a|
|at0054| 0..1| DV_TEXT | Behandlingsprotokoll
a|
|at0033| 0..*| DV_CODED_TEXT | Klinisk indikasjon
a|
* Primær malign tumor (disorder) (no.onk.kreftgruppering: 372087000)
* Residiv av malign tumor (disorder) (no.onk.kreftgruppering: 1259237005)
* Metastase malign tumor (disorder) (no.onk.kreftgruppering: 128462008)
* Komplikasjon av medisinsk behandling (disorder) (no.onk.kreftgruppering: 35688006)
* Annen (qualifier value) (no.onk.kreftgruppering: 74964007)
* Primærtumor (ikke malign eller beningn) (no.onk.kreftgruppering: ???)
* Tumor (morphologic abnormality) (no.onk.kreftgruppering: 108369006)
* Tumor, benign (morphologic abnormality) (no.onk.kreftgruppering: 3898006)
* Tumor, malign (morphological abnormality) (no.onk.kreftgruppering: 1240414004)


Koding av "Klinisk indikasjon" med en terminologi er foretrukket, dersom det er mulig.
Dette dataelementet tillater flere forekomster, slik at det kan registrere en eller flere indikasjoner ved behov.
|at0034| 0..1| DV_CODED_TEXT | Intensjon
a|
* Kurativt (no.onk.behandlingsintensjon: K1)
* Aktiv overvåkning (no.onk.behandlingsintensjon: K2)
* Livsforlengende - ikke kurativ (no.onk.behandlingsintensjon: K3)
* Symptomlindrende - ikke kurativ (no.onk.behandlingsintensjon: K4)
* Lokal kontroll - ikke kurativ (no.onk.behandlingsintensjon: K5)
* Ukjent (no.onk.behandlingsintensjon: K6)


For eksempel: kurativ, palliativ eller preventiv hensikt. 
Koding av "intensjon med en terminologi er foretrukket, dersom det er mulig.
Dette dataelementet tillater flere forekomster, slik at det er mulig å registrere en eller flere alternativer ved behov.
|at0055| 0..*| DV_CODED_TEXT | Treatment line
a|
* First line treatment (SNOMED-CT: 708255002)
* Second line treatment (SNOMED-CT: 708256001)
* Third line treatment (SNOMED-CT: 708257005)


For eksempel: neoadjuvant, concomitant (samtidig) og adjuvant.
|at0032| 0..1| DV_DATE_TIME | Start behandlingsforløp
|
|at0004| 0..1| DV_DATE_TIME | Stopp behandlingsforløp
|
|at0005| 0..1| DV_CODED_TEXT | Fullføringsstatus
a|
* at0021 -> Fullført 
* at0022 -> Ikke fullført 
|at0007| 0..1| DV_TEXT | Årsak til ikke fullført
a|


Koding med en terminologi er foretrukket, dersom det er mulig.
|at0008| 0..1| DV_TEXT | Resultatkategori
a|
* Vellykket i henhold til intensjon
* Ikke vellykket i henhold til intensjon


For eksempel: vellykket, ikke vellykket, usikkert.
Koding med en terminologi er foretrukket, dersom det er mulig.
|at0027| 0..1| DV_TEXT | Årsak til resultatkategori
a|


For eksempel: resistens mot medikament.
|at0018| 0..1| DV_DATE_TIME | Sist oppdatert
|
|====
== Hovedbehandling
== Invasiv prosedyre
== Intervensjonssammendrag
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Intervensjonssammendrag* + 
EVALUATION: _openEHR-EHR-EVALUATION.intervention_summary.v0_
|at0003| 1..1| DV_CODED_TEXT | Intervensjon navn
a|
* Eksisjon (reseksjon) (no.onk.intervensjon.prosedyre: 65801008)
* Reeksisjon (ny utskjæring) (no.onk.intervensjon.prosedyre: 65854006)
* Amputasjon (no.onk.intervensjon.prosedyre: 81723002)
* Curettage (no.onk.intervensjon.prosedyre: 68688001)
* Revisjon (gjentakelse av tidligere prosedyre for å korrigere eller forbedre resultat) (no.onk.intervensjon.prosedyre: 118635009)
* Annet (no.onk.intervensjon.prosedyre: 74964007)


*For example: antibiotic, radiotherapy.
Coding with an external terminology is preferred, where possible.

exact treatment, Dette er den faktiske behandlingen, navnet til denne.  (en)
|at0058| 0..1| DV_CODED_TEXT | Intervensjonstype
a|
* Kirurgisk inngrep (SNOMED-CT: 387713003)


Dette dataelementet kan brukes til å støtte organisering innenfor brukergrensesnittet.
|at0028| 0..1| DV_TEXT | Beskrivelse
a|
|at0054| 0..1| DV_TEXT | Protokollnavn
a|


Designkommentar:
arver fra toppnivå
|at0033| 0..*| DV_TEXT | Indikasjon for behandling/behandlingsgrunnlag
a|


Koding av "Klinisk indikasjon" med en terminologi er foretrukket, dersom det er mulig.
Dette dataelementet tillater flere forekomster, slik at det kan registrere en eller flere indikasjoner ved behov.
|at0055| 0..*| DV_CODED_TEXT | Terapautisk rolle
a|
* Hovedbehandling (no.onk.behandling.kategori: 1)


*For example: neoadjuvant, concomitant or adjuvant. main treatment, additional (en)
|at0032| 0..1| DV_DATE_TIME | Intervensjonsdato
|
5+a|*Anatomisk lokalisering* + 
CLUSTER: _openEHR-EHR-CLUSTER.anatomical_location.v1_
|at0001| 1..1| DV_TEXT | Navn på kroppssted
a|


Dette dataelementet er det eneste obligatoriske dataelementet i arketypen og bør brukes som det primære dataelementet for registrering av en anatomisk lokalisering. Det er sterkt anbefalt at "Navn på kroppssted" registreres så anatomisk spesifikt som mulig. For eksempel; registrer "øvre øyelokk" heller enn "øyelokk" med "øvre" som kvalifikator; "femte ribben" heller enn "ribben" med en numerisk kvalifikator. Bruk de andre dataelementene for lateralitet, aspekt, region og anatomisk linje for å gi mer detaljer. Dette dataelementet bør kodes med en terminologi som kan assistere beslutningsstøtte dersom mulig - en passende terminologi for bruk her kunne omfatte individuelle konsepter eller lister av prekoordinerte termer. Fritekst bør kun brukes hvis det ikke finnes en passende terminologi. 

Dersom navn på kroppssted er oppgitt i arketypen som denne arketypen er nøstet inn i, kan dette dataelementet være redundant. Imidlertid kan det være fornuftig å dobbeltregistrere navnet på kroppstedet for å støtte semantiske spørringer basert på denne arketypen i stedet for i arketypen den er nøstet inn i.
|at0065| 0..*| DV_TEXT | Spesifikt sted
a|


Brukes til å øke presisjonen ved spesifisering av kroppsstedet, dersom påkrevd. For eksempel den øvre høyre kvadranten eller McBurneys punkt på bukveggen, eller interfalangealleddet på stortåen. Dersom dataelementet "Navn på kroppssted" er registrert ved hjelp av prekoordinerte termer som omfatter det spesifikke stedet er dette dataelementet overflødig. I de fleste tilfeller vil dette være ett enkelt sted på kroppen. Dataelementet åpner for flere forekomster i de sjeldne tilfellene der man trenger å angi et spesifikt anatomisk sted som omfatter to eller flere sammenhengende spesifikke steder. For eksempel for å beskrive det spesifikke stedet en svulst strekker seg over andre, tredje og fjerde ribben.
|at0002| 0..1| DV_CODED_TEXT | Kroppsside
a|
* at0003 -> Venstre 
* at0004 -> Høyre 
* at0083 -> Venstre og høyre 


Hvis «Navn på kroppssted» inkluderer et pre-koordinert begrep som allerede angir lateralitet, kan dette dataelementet være overflødig. Hvis funnene krever dokumentasjon av et kroppssted på både venstre og høyre side av kroppen, eller involverer begge sider av en parret struktur eller region, bruk «Venstre og høyre» kun når samme anatomiske sted er involvert på begge sider og side-spesifikke detaljer ikke er nødvendige. Hvis funnene er betydelig forskjellige mellom sidene, bør hver side dokumenteres som en separat instans av denne arketypen med korrekt lateralitet.
|at0018| 0..1| DV_DATE_TIME | Sist oppdatert
|
|====
== Medikamentell
== Templat-overskrift
== Intervensjonssammendrag
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Intervensjonssammendrag* + 
EVALUATION: _openEHR-EHR-EVALUATION.intervention_summary.v0_
|at0003| 1..1| DV_CODED_TEXT | Intervensjon navn
a|
* Kjemoterapi - Medikamentell (SNOMED-CT: 367336001)
* Målrettet - Medikamentell (SNOMED-CT: 347531000202105)
* Immunterapi for kreft - Medikamentell (SNOMED-CT: 64644003)
* Hormonterapi – Medikamentell (SNOMED-CT: 169413002)


*For example: antibiotic, radiotherapy.
Coding with an external terminology is preferred, where possible.

exact treatment, Dette er den faktiske behandlingen, navnet til denne.  (en)
|at0058| 0..1| DV_CODED_TEXT | Intervensjonstype
a|
* Medikamentell behandling (procedure) (SNOMED-CT: 416608005)


Dette dataelementet kan brukes til å støtte organisering innenfor brukergrensesnittet.
|at0028| 0..1| DV_TEXT | Beskrivelse
a|
|at0054| 0..1| DV_TEXT | Protokollnavn
a|
|at0055| 0..*| DV_CODED_TEXT | Terapautisk rolle
a|
* Hovedbehandling (no.onk.behandling.kategori: 1)


*For example: neoadjuvant, concomitant or adjuvant. main treatment, additional (en)
|at0032| 0..1| DV_DATE_TIME | Start dato
|
|at0004| 0..1| DV_DATE_TIME | Stopp dato
|
|at0005| 0..1| DV_CODED_TEXT | Fullføringsstatus
a|
* at0021 -> Fullført 
* at0022 -> Ikke fullført 
|at0007| 0..1| DV_TEXT | Årsak til ikke fullført
a|


Koding med en terminologi er foretrukket, dersom det er mulig.
|at0018| 0..1| DV_DATE_TIME | Sist oppdatert
|
|====
== Legemiddelsammendrag
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Legemiddelsammendrag* + 
EVALUATION: _openEHR-EHR-EVALUATION.medication_summary.v1_
|at0002| 1..1| DV_TEXT | Navn på kur/medikament
a|


Navn på legemiddel kan representeres som en generisk substans, handelsnavn, gruppe eller klasse av legemidler. Det anbefales å kode "Navn på legemiddel" med en terminologi om mulig, slik at det kan brukes for eksempel i beslutningsstøtte. Fritekst bør bare benyttes der det ikke finnes en passende terminologi.
For eksempel: '"Adriamycin"; "doxorubicin" eller "anthracycliner"; "Fosamax", "alendronsyre" eller "bifosonater".
|at0009| 0..1| DV_DATE_TIME | Startdato for bruk
|


Kan være en deldato, for eksempel kun årstall.
|at0015| 0..1| DV_QUANTITY | Kumulativ mengde
|


For eksempel: monitorering av kumulativ mengde av doxorubicin.
Kan regnes ut manuelt eller utledes via ulike kilder, som for eksempel kurvesystemet eller andre deler av den elektroniske pasientjournalen.
|at0010| 0..1| DV_DATE_TIME | Sluttdato for bruk
|


Kan være en deldato, for eksempel kun årstall.
|at0006| 0..1| DV_DATE_TIME | Sist oppdatert
|
|====
== Stråleterapi
== Intervensjonssammendrag
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Intervensjonssammendrag* + 
EVALUATION: _openEHR-EHR-EVALUATION.intervention_summary.v0_
|at0003| 1..1| DV_CODED_TEXT | Intervensjon navn
a|
* Strålebehandling (no.onk.intervensjon.straaleterapi: 1287742003)
* Fotonterapi - Stråle (ekstern) (no.onk.intervensjon.straaleterapi: 1156506007)
* Protonterapi -Stråle (ekstern) (no.onk.intervensjon.straaleterapi: 169314007)
* Elektronterapi - Stråle (ekstern) (no.onk.intervensjon.straaleterapi: 45643008)
* Brakyterapi - Stråle (intern) (no.onk.intervensjon.straaleterapi: 152198000)
* Radioisotope/systemisk radionuklidebehandling - Stråle (intern) (no.onk.intervensjon.straaleterapi: 399315003)
* Partikkelstråleterapi (karbon eller proton) (no.onk.intervensjon.straaleterapi: WEOC)
* Karbonterapi (no.onk.intervensjon.straaleterapi: WEOC10)
* Protonterapi (NKPK) (no.onk.intervensjon.straaleterapi: WEOC00)
* Ekstern stråleterapi (no.onk.intervensjon.straaleterapi: WEOA)
* Brakyterapi (no.onk.intervensjon.straaleterapi: WEOB)
* Stråleterapi (no.onk.intervensjon.straaleterapi: WE)


*For example: antibiotic, radiotherapy.
Coding with an external terminology is preferred, where possible.

exact treatment, Dette er den faktiske behandlingen, navnet til denne.  (en)
|at0058| 0..1| DV_CODED_TEXT | Intervensjonstype
a|
* Strålebehandling (SNOMED-CT: 1287742003)


Dette dataelementet kan brukes til å støtte organisering innenfor brukergrensesnittet.
|at0028| 0..1| DV_TEXT | Beskrivelse av stråleintervensjonen
a|
|at0054| 0..1| DV_TEXT | Protokollnavn
a|
|at0055| 0..*| DV_CODED_TEXT | Terapautisk rolle
a|
* Hovedbehandling (no.onk.behandling.kategori: 1)


*For example: neoadjuvant, concomitant or adjuvant. main treatment, additional (en)
|at0032| 0..1| DV_DATE_TIME | Dato første fraksjon
|
|at0004| 0..1| DV_DATE_TIME | Dato siste fraksjon
|
|at0005| 0..1| DV_CODED_TEXT | Fullføringsstatus
a|
* at0021 -> Fullført 
* at0022 -> Ikke fullført 
|at0007| 0..1| DV_TEXT | Årsak til ikke fullført
a|


Koding med en terminologi er foretrukket, dersom det er mulig.
|at0018| 0..1| DV_DATE_TIME | Sist oppdatert
|
|at0057| 0..1| DV_TEXT | Stråleterapi course ID
a|
|====
== Tilleggsbehandling
== Invasiv prosedyre
== Intervensjonssammendrag
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Intervensjonssammendrag* + 
EVALUATION: _openEHR-EHR-EVALUATION.intervention_summary.v0_
|at0003| 1..1| DV_CODED_TEXT | Intervensjon navn
a|
* Eksisjon (reseksjon) (no.onk.intervensjon.prosedyre: 65801008)
* Reeksisjon (ny utskjæring) (no.onk.intervensjon.prosedyre: 65854006)
* Amputasjon (no.onk.intervensjon.prosedyre: 81723002)
* Curettage (no.onk.intervensjon.prosedyre: 68688001)
* Revisjon (gjentakelse av tidligere prosedyre for å korrigere eller forbedre resultat) (no.onk.intervensjon.prosedyre: 118635009)
* Annet (no.onk.intervensjon.prosedyre: 74964007)


*For example: antibiotic, radiotherapy.
Coding with an external terminology is preferred, where possible.

exact treatment, Dette er den faktiske behandlingen, navnet til denne.  (en)
|at0058| 0..1| DV_CODED_TEXT | Intervensjonstype
a|
* Kirurgisk inngrep (SNOMED-CT: 387713003)


Dette dataelementet kan brukes til å støtte organisering innenfor brukergrensesnittet.
|at0028| 0..1| DV_TEXT | Beskrivelse
a|
|at0054| 0..1| DV_TEXT | Protokollnavn
a|


Designkommentar:
arver fra toppnivå
|at0055| 0..*| DV_CODED_TEXT | Terapautisk rolle
a|
* Adjuvant hensikt (SNOMED-CT: 373846009)
* Neoadjuvant hensikt (SNOMED-CT: 373847000)
* Konkomitant (adjunkt) hensikt) (SNOMED-CT: 421974008)


*For example: neoadjuvant, concomitant or adjuvant. main treatment, additional (en)
|at0032| 0..1| DV_DATE_TIME | Intervensjonsdato
|
5+a|*Anatomisk lokalisering* + 
CLUSTER: _openEHR-EHR-CLUSTER.anatomical_location.v1_
|at0001| 1..1| DV_TEXT | Navn på kroppssted
a|


Dette dataelementet er det eneste obligatoriske dataelementet i arketypen og bør brukes som det primære dataelementet for registrering av en anatomisk lokalisering. Det er sterkt anbefalt at "Navn på kroppssted" registreres så anatomisk spesifikt som mulig. For eksempel; registrer "øvre øyelokk" heller enn "øyelokk" med "øvre" som kvalifikator; "femte ribben" heller enn "ribben" med en numerisk kvalifikator. Bruk de andre dataelementene for lateralitet, aspekt, region og anatomisk linje for å gi mer detaljer. Dette dataelementet bør kodes med en terminologi som kan assistere beslutningsstøtte dersom mulig - en passende terminologi for bruk her kunne omfatte individuelle konsepter eller lister av prekoordinerte termer. Fritekst bør kun brukes hvis det ikke finnes en passende terminologi. 

Dersom navn på kroppssted er oppgitt i arketypen som denne arketypen er nøstet inn i, kan dette dataelementet være redundant. Imidlertid kan det være fornuftig å dobbeltregistrere navnet på kroppstedet for å støtte semantiske spørringer basert på denne arketypen i stedet for i arketypen den er nøstet inn i.
|at0065| 0..*| DV_TEXT | Spesifikt sted
a|


Brukes til å øke presisjonen ved spesifisering av kroppsstedet, dersom påkrevd. For eksempel den øvre høyre kvadranten eller McBurneys punkt på bukveggen, eller interfalangealleddet på stortåen. Dersom dataelementet "Navn på kroppssted" er registrert ved hjelp av prekoordinerte termer som omfatter det spesifikke stedet er dette dataelementet overflødig. I de fleste tilfeller vil dette være ett enkelt sted på kroppen. Dataelementet åpner for flere forekomster i de sjeldne tilfellene der man trenger å angi et spesifikt anatomisk sted som omfatter to eller flere sammenhengende spesifikke steder. For eksempel for å beskrive det spesifikke stedet en svulst strekker seg over andre, tredje og fjerde ribben.
|at0002| 0..1| DV_CODED_TEXT | Kroppsside
a|
* at0003 -> Venstre 
* at0004 -> Høyre 
* at0083 -> Venstre og høyre 


Hvis «Navn på kroppssted» inkluderer et pre-koordinert begrep som allerede angir lateralitet, kan dette dataelementet være overflødig. Hvis funnene krever dokumentasjon av et kroppssted på både venstre og høyre side av kroppen, eller involverer begge sider av en parret struktur eller region, bruk «Venstre og høyre» kun når samme anatomiske sted er involvert på begge sider og side-spesifikke detaljer ikke er nødvendige. Hvis funnene er betydelig forskjellige mellom sidene, bør hver side dokumenteres som en separat instans av denne arketypen med korrekt lateralitet.
|at0018| 0..1| DV_DATE_TIME | Sist oppdatert
|
|====
== Medikamentell
== Templat-overskrift
== Intervensjonssammendrag
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Intervensjonssammendrag* + 
EVALUATION: _openEHR-EHR-EVALUATION.intervention_summary.v0_
|at0003| 1..1| DV_CODED_TEXT | Intervensjon navn
a|
* Kjemoterapi - Medikamentell (SNOMED-CT: 367336001)
* Målrettet - Medikamentell (SNOMED-CT: 347531000202105)
* Immunterapi for kreft - Medikamentell (SNOMED-CT: 64644003)
* Hormonterapi – Medikamentell (SNOMED-CT: 169413002)


*For example: antibiotic, radiotherapy.
Coding with an external terminology is preferred, where possible.

exact treatment, Dette er den faktiske behandlingen, navnet til denne.  (en)
|at0058| 0..1| DV_CODED_TEXT | Intervensjonstype
a|
* Medikamentell behandling (procedure) (SNOMED-CT: 416608005)


Dette dataelementet kan brukes til å støtte organisering innenfor brukergrensesnittet.
|at0028| 0..1| DV_TEXT | Beskrivelse
a|
|at0054| 0..1| DV_TEXT | Protokollnavn
a|
|at0055| 0..*| DV_CODED_TEXT | Terapautisk rolle
a|
* Adjuvant hensikt (SNOMED-CT: 373846009)
* Neoadjuvant hensikt (SNOMED-CT: 373847000)
* Konkomitant (adjunkt) hensikt) (SNOMED-CT: 421974008)


*For example: neoadjuvant, concomitant or adjuvant. main treatment, additional (en)
|at0032| 0..1| DV_DATE_TIME | Start dato
|
|at0004| 0..1| DV_DATE_TIME | Stopp dato
|
|at0005| 0..1| DV_CODED_TEXT | Fullføringsstatus
a|
* at0021 -> Fullført 
* at0022 -> Ikke fullført 
|at0007| 0..1| DV_TEXT | Årsak til ikke fullført
a|


Koding med en terminologi er foretrukket, dersom det er mulig.
|at0018| 0..1| DV_DATE_TIME | Sist oppdatert
|
|====
== Legemiddelsammendrag
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Legemiddelsammendrag* + 
EVALUATION: _openEHR-EHR-EVALUATION.medication_summary.v1_
|at0002| 1..1| DV_TEXT | Navn på kur/medikament
a|


Navn på legemiddel kan representeres som en generisk substans, handelsnavn, gruppe eller klasse av legemidler. Det anbefales å kode "Navn på legemiddel" med en terminologi om mulig, slik at det kan brukes for eksempel i beslutningsstøtte. Fritekst bør bare benyttes der det ikke finnes en passende terminologi.
For eksempel: '"Adriamycin"; "doxorubicin" eller "anthracycliner"; "Fosamax", "alendronsyre" eller "bifosonater".
|at0009| 0..1| DV_DATE_TIME | Startdato for bruk
|


Kan være en deldato, for eksempel kun årstall.
|at0015| 0..1| DV_QUANTITY | Kumulativ mengde
|


For eksempel: monitorering av kumulativ mengde av doxorubicin.
Kan regnes ut manuelt eller utledes via ulike kilder, som for eksempel kurvesystemet eller andre deler av den elektroniske pasientjournalen.
|at0010| 0..1| DV_DATE_TIME | Sluttdato for bruk
|


Kan være en deldato, for eksempel kun årstall.
|at0006| 0..1| DV_DATE_TIME | Sist oppdatert
|
|====
== Stråleterapi
== Intervensjonssammendrag
[options="header", cols="3,3,5,5,30"]
|====
|NodeId|Attr.|RM Type| Name |Description
5+a|*Intervensjonssammendrag* + 
EVALUATION: _openEHR-EHR-EVALUATION.intervention_summary.v0_
|at0003| 1..1| DV_CODED_TEXT | Intervensjon navn
a|
* Strålebehandling (no.onk.intervensjon.straaleterapi: 1287742003)
* Fotonterapi - Stråle (ekstern) (no.onk.intervensjon.straaleterapi: 1156506007)
* Protonterapi -Stråle (ekstern) (no.onk.intervensjon.straaleterapi: 169314007)
* Elektronterapi - Stråle (ekstern) (no.onk.intervensjon.straaleterapi: 45643008)
* Brakyterapi - Stråle (intern) (no.onk.intervensjon.straaleterapi: 152198000)
* Radioisotope/systemisk radionuklidebehandling - Stråle (intern) (no.onk.intervensjon.straaleterapi: 399315003)
* Partikkelstråleterapi (karbon eller proton) (no.onk.intervensjon.straaleterapi: WEOC)
* Karbonterapi (no.onk.intervensjon.straaleterapi: WEOC10)
* Protonterapi (NKPK) (no.onk.intervensjon.straaleterapi: WEOC00)
* Ekstern stråleterapi (no.onk.intervensjon.straaleterapi: WEOA)
* Brakyterapi (no.onk.intervensjon.straaleterapi: WEOB)
* Stråleterapi (no.onk.intervensjon.straaleterapi: WE)


*For example: antibiotic, radiotherapy.
Coding with an external terminology is preferred, where possible.

exact treatment, Dette er den faktiske behandlingen, navnet til denne.  (en)
|at0058| 0..1| DV_CODED_TEXT | Intervensjonstype
a|
* Strålebehandling (SNOMED-CT: 1287742003)


Dette dataelementet kan brukes til å støtte organisering innenfor brukergrensesnittet.
|at0028| 0..1| DV_TEXT | Beskrivelse av stråleintervensjonen
a|
|at0054| 0..1| DV_TEXT | Protokollnavn
a|
|at0055| 0..*| DV_CODED_TEXT | Terapautisk rolle
a|
* Adjuvant hensikt (SNOMED-CT: 373846009)
* Neoadjuvant hensikt (SNOMED-CT: 373847000)
* Konkomitant (adjunkt) hensikt) (SNOMED-CT: 421974008)


*For example: neoadjuvant, concomitant or adjuvant. main treatment, additional (en)
|at0032| 0..1| DV_DATE_TIME | Dato første fraksjon
|
|at0004| 0..1| DV_DATE_TIME | Dato siste fraksjon
|
|at0005| 0..1| DV_CODED_TEXT | Fullføringsstatus
a|
* at0021 -> Fullført 
* at0022 -> Ikke fullført 
|at0007| 0..1| DV_TEXT | Årsak til ikke fullført
a|


Koding med en terminologi er foretrukket, dersom det er mulig.
|at0018| 0..1| DV_DATE_TIME | Sist oppdatert
|
|at0057| 0..1| DV_TEXT | Stråleterapi course ID
a|
|====
// Not supported rmType CODE_PHRASE
// Not supported rmType CODE_PHRASE
// Not supported rmType PARTY_PROXY